"""Admin Roles endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class AdminRolesResource:
    """Admin Roles endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def get_roles(
        self, *, search: str | None = None, offset: int | None = None, limit: int | None = None, sort: str | None = None
    ) -> models.AdminRolesResponse:
        """Get Roles.

        List all roles.

        ``GET /api/admin-roles``

        Args:
            search: Query parameter.
            offset: Query parameter.
            limit: Query parameter.
            sort: Query parameter.

        Returns:
            models.AdminRolesResponse
        """
        path = "/api/admin-roles"
        params = _clean({"search": search, "offset": offset, "limit": limit, "sort": sort})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.AdminRolesResponse.model_validate(data)

    async def get_roles_simple(self) -> models.AdminRolesSimpleResponse:
        """Get Roles Simple.

        List all roles as lightweight id/name/is_owner tuples.

        ``GET /api/admin-roles/simple``

        Returns:
            models.AdminRolesSimpleResponse
        """
        path = "/api/admin-roles/simple"
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.AdminRolesSimpleResponse.model_validate(data)

    async def get_role(self, role_id: int) -> models.AdminRoleResponse:
        """Get Role.

        Get a role by ID.

        ``GET /api/admin-role/{role_id}``

        Args:
            role_id:

        Returns:
            models.AdminRoleResponse
        """
        path = _fmt("/api/admin-role/{role_id}", {"role_id": role_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.AdminRoleResponse.model_validate(data)

    async def modify_role(
        self, role_id: int, *, body: models.AdminRoleModify | dict[str, Any]
    ) -> models.AdminRoleResponse:
        """Modify Role.

        Modify a role. Owner only. Owner role cannot be modified.

        ``PUT /api/admin-role/{role_id}``

        Args:
            role_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.AdminRoleResponse
        """
        path = _fmt("/api/admin-role/{role_id}", {"role_id": role_id})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.AdminRoleResponse.model_validate(data)

    async def delete_role(self, role_id: int) -> None:
        """Delete Role.

        Delete a role. Owner only. Built-in roles and in-use roles cannot be deleted.

        ``DELETE /api/admin-role/{role_id}``

        Args:
            role_id:

        Returns:
            None
        """
        path = _fmt("/api/admin-role/{role_id}", {"role_id": role_id})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def create_role(self, *, body: models.AdminRoleCreate | dict[str, Any]) -> models.AdminRoleResponse:
        """Create Role.

        Create a new role. Owner only.

        ``POST /api/admin-role``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.AdminRoleResponse
        """
        path = "/api/admin-role"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.AdminRoleResponse.model_validate(data)
