"""Admin endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class AdminResource:
    """Admin endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def admin_token(
        self,
        *,
        username: str,
        password: str,
        otp: str | None = None,
        grant_type: str | None = None,
        scope: str | None = None,
        client_id: str | None = None,
        client_secret: str | None = None,
    ) -> models.Token:
        """Admin Token.

        Authenticate an admin and issue a token; admins with two-factor on also send ``otp``.

        ``POST /api/admin/token``

        Args:
            username: Form field.
            password: Form field.
            otp: Form field.
            grant_type: Form field.
            scope: Form field.
            client_id: Form field.
            client_secret: Form field.

        Returns:
            models.Token
        """
        path = "/api/admin/token"
        params = None
        headers = None
        data = await self._http.request(
            "post",
            path,
            params=params,
            headers=headers,
            data=_clean(
                {
                    "otp": otp,
                    "grant_type": grant_type,
                    "username": username,
                    "password": password,
                    "scope": scope,
                    "client_id": client_id,
                    "client_secret": client_secret,
                }
            ),
        )
        return models.Token.model_validate(data)

    async def totp_setup(self) -> models.TotpSetup:
        """Totp Setup.

        Start two-factor enrolment: a new secret to scan; it only counts once a code confirms it.

        ``POST /api/admin/totp/setup``

        Returns:
            models.TotpSetup
        """
        path = "/api/admin/totp/setup"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.TotpSetup.model_validate(data)

    async def totp_enable(self, *, body: models.TotpCode | dict[str, Any]) -> None:
        """Totp Enable.

        Confirm the scanned secret with a code; from now on sign-in needs it.

        ``POST /api/admin/totp/enable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            None
        """
        path = "/api/admin/totp/enable"
        params = None
        headers = None
        await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return None

    async def totp_disable(self, *, body: models.TotpCode | dict[str, Any]) -> None:
        """Totp Disable.

        Turn two-factor off for the signed-in admin; needs a current code.

        ``POST /api/admin/totp/disable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            None
        """
        path = "/api/admin/totp/disable"
        params = None
        headers = None
        await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return None

    async def totp_reset(self, username: str) -> None:
        """Totp Reset.

        Recovery: an admin with admin-update rights clears another admin's two-factor.

        ``DELETE /api/admin/{username}/totp``

        Args:
            username:

        Returns:
            None
        """
        path = _fmt("/api/admin/{username}/totp", {"username": username})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def admin_mini_app_token(self, *, x_telegram_authorization: str) -> Any:
        """Admin Mini App Token.

        Authenticate an admin via Telegram MiniApp and issue a token.

        ``POST /api/admin/miniapp/token``

        Args:
            x_telegram_authorization: Header ``x-telegram-authorization``.

        Returns:
            Any
        """
        path = "/api/admin/miniapp/token"
        params = None
        headers = _clean({"x-telegram-authorization": x_telegram_authorization})
        return await self._http.request("post", path, params=params, headers=headers)

    async def get_current_admin(self) -> models.AdminDetails:
        """Get Current Admin.

        Retrieve the current authenticated admin.

        ``GET /api/admin``

        Returns:
            models.AdminDetails
        """
        path = "/api/admin"
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.AdminDetails.model_validate(data)

    async def create_admin(self, *, body: models.AdminCreate | dict[str, Any]) -> models.AdminDetails:
        """Create Admin.

        Create a new admin.

        ``POST /api/admin``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.AdminDetails
        """
        path = "/api/admin"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.AdminDetails.model_validate(data)

    async def modify_admin(self, username: str, *, body: models.AdminModify | dict[str, Any]) -> models.AdminDetails:
        """Modify Admin.

        Modify an existing admin's details.

        ``PUT /api/admin/{username}``

        Args:
            username:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.AdminDetails
        """
        path = _fmt("/api/admin/{username}", {"username": username})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.AdminDetails.model_validate(data)

    async def remove_admin(self, username: str) -> None:
        """Remove Admin.

        Remove an admin from the database.

        ``DELETE /api/admin/{username}``

        Args:
            username:

        Returns:
            None
        """
        path = _fmt("/api/admin/{username}", {"username": username})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def modify_admin_by_username(
        self, username: str, *, body: models.AdminModify | dict[str, Any]
    ) -> models.AdminDetails:
        """Modify Admin By Username.

        ``PUT /api/admin/by-username/{username}``

        Args:
            username:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.AdminDetails
        """
        path = _fmt("/api/admin/by-username/{username}", {"username": username})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.AdminDetails.model_validate(data)

    async def remove_admin_by_username(self, username: str) -> None:
        """Remove Admin By Username.

        ``DELETE /api/admin/by-username/{username}``

        Args:
            username:

        Returns:
            None
        """
        path = _fmt("/api/admin/by-username/{username}", {"username": username})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def modify_admin_by_id(
        self, admin_id: int, *, body: models.AdminModify | dict[str, Any]
    ) -> models.AdminDetails:
        """Modify Admin By Id.

        ``PUT /api/admin/by-id/{admin_id}``

        Args:
            admin_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.AdminDetails
        """
        path = _fmt("/api/admin/by-id/{admin_id}", {"admin_id": admin_id})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.AdminDetails.model_validate(data)

    async def remove_admin_by_id(self, admin_id: int) -> None:
        """Remove Admin By Id.

        ``DELETE /api/admin/by-id/{admin_id}``

        Args:
            admin_id:

        Returns:
            None
        """
        path = _fmt("/api/admin/by-id/{admin_id}", {"admin_id": admin_id})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def get_admins(
        self,
        *,
        ids: list[int] | None = None,
        usernames: list[str] | None = None,
        username: str | None = None,
        offset: int | None = None,
        limit: int | None = None,
        sort: str | None = None,
    ) -> models.AdminsResponse:
        """Get Admins.

        Fetch a list of admins with optional filters for pagination and username.

        ``GET /api/admins``

        Args:
            ids: Query parameter.
            usernames: Query parameter.
            username: Query parameter.
            offset: Query parameter.
            limit: Query parameter.
            sort: Query parameter.

        Returns:
            models.AdminsResponse
        """
        path = "/api/admins"
        params = _clean(
            {"ids": ids, "usernames": usernames, "username": username, "offset": offset, "limit": limit, "sort": sort}
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.AdminsResponse.model_validate(data)

    async def get_admins_simple(
        self,
        *,
        ids: list[int] | None = None,
        usernames: list[str] | None = None,
        search: str | None = None,
        offset: int | None = None,
        limit: int | None = None,
        sort: str | None = None,
        all: bool | None = None,
    ) -> models.AdminsSimpleResponse:
        """Get lightweight admin list.

        Returns only id and username for admins. Optimized for dropdowns and autocomplete.

        ``GET /api/admins/simple``

        Args:
            ids: Query parameter.
            usernames: Query parameter.
            search: Query parameter.
            offset: Query parameter.
            limit: Query parameter.
            sort: Query parameter.
            all: Query parameter.

        Returns:
            models.AdminsSimpleResponse
        """
        path = "/api/admins/simple"
        params = _clean(
            {
                "ids": ids,
                "usernames": usernames,
                "search": search,
                "offset": offset,
                "limit": limit,
                "sort": sort,
                "all": all,
            }
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.AdminsSimpleResponse.model_validate(data)

    async def get_admin_usage(
        self,
        username: str,
        *,
        period: models.Period | None = None,
        node_id: int | None = None,
        group_by_node: bool | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
    ) -> models.UserUsageStatsList:
        """Get Admin Usage.

        Get admin usage aggregated from user traffic.

        ``GET /api/admin/{username}/usage``

        Args:
            username:
            period: Query parameter.
            node_id: Query parameter.
            group_by_node: Query parameter.
            start: Query parameter.
            end: Query parameter.

        Returns:
            models.UserUsageStatsList
        """
        path = _fmt("/api/admin/{username}/usage", {"username": username})
        params = _clean(
            {"period": period, "node_id": node_id, "group_by_node": group_by_node, "start": start, "end": end}
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserUsageStatsList.model_validate(data)

    async def get_admin_usage_by_username(
        self,
        username: str,
        *,
        period: models.Period | None = None,
        node_id: int | None = None,
        group_by_node: bool | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
    ) -> models.UserUsageStatsList:
        """Get Admin Usage By Username.

        ``GET /api/admin/by-username/{username}/usage``

        Args:
            username:
            period: Query parameter.
            node_id: Query parameter.
            group_by_node: Query parameter.
            start: Query parameter.
            end: Query parameter.

        Returns:
            models.UserUsageStatsList
        """
        path = _fmt("/api/admin/by-username/{username}/usage", {"username": username})
        params = _clean(
            {"period": period, "node_id": node_id, "group_by_node": group_by_node, "start": start, "end": end}
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserUsageStatsList.model_validate(data)

    async def get_admin_usage_by_id(
        self,
        admin_id: int,
        *,
        period: models.Period | None = None,
        node_id: int | None = None,
        group_by_node: bool | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
    ) -> models.UserUsageStatsList:
        """Get Admin Usage By Id.

        ``GET /api/admin/by-id/{admin_id}/usage``

        Args:
            admin_id:
            period: Query parameter.
            node_id: Query parameter.
            group_by_node: Query parameter.
            start: Query parameter.
            end: Query parameter.

        Returns:
            models.UserUsageStatsList
        """
        path = _fmt("/api/admin/by-id/{admin_id}/usage", {"admin_id": admin_id})
        params = _clean(
            {"period": period, "node_id": node_id, "group_by_node": group_by_node, "start": start, "end": end}
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserUsageStatsList.model_validate(data)

    async def disable_all_active_users(self, username: str) -> Any:
        """Disable All Active Users.

        Disable all active users under a specific admin.

        ``POST /api/admin/{username}/users/disable``

        Args:
            username:

        Returns:
            Any
        """
        path = _fmt("/api/admin/{username}/users/disable", {"username": username})
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers)

    async def disable_all_active_users_by_username(self, username: str) -> Any:
        """Disable All Active Users By Username.

        ``POST /api/admin/by-username/{username}/users/disable``

        Args:
            username:

        Returns:
            Any
        """
        path = _fmt("/api/admin/by-username/{username}/users/disable", {"username": username})
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers)

    async def disable_all_active_users_by_id(self, admin_id: int) -> Any:
        """Disable All Active Users By Id.

        ``POST /api/admin/by-id/{admin_id}/users/disable``

        Args:
            admin_id:

        Returns:
            Any
        """
        path = _fmt("/api/admin/by-id/{admin_id}/users/disable", {"admin_id": admin_id})
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers)

    async def activate_all_disabled_users(self, username: str) -> Any:
        """Activate All Disabled Users.

        Activate all disabled users under a specific admin.

        ``POST /api/admin/{username}/users/activate``

        Args:
            username:

        Returns:
            Any
        """
        path = _fmt("/api/admin/{username}/users/activate", {"username": username})
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers)

    async def activate_all_disabled_users_by_username(self, username: str) -> Any:
        """Activate All Disabled Users By Username.

        ``POST /api/admin/by-username/{username}/users/activate``

        Args:
            username:

        Returns:
            Any
        """
        path = _fmt("/api/admin/by-username/{username}/users/activate", {"username": username})
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers)

    async def activate_all_disabled_users_by_id(self, admin_id: int) -> Any:
        """Activate All Disabled Users By Id.

        ``POST /api/admin/by-id/{admin_id}/users/activate``

        Args:
            admin_id:

        Returns:
            Any
        """
        path = _fmt("/api/admin/by-id/{admin_id}/users/activate", {"admin_id": admin_id})
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers)

    async def remove_all_users(self, username: str) -> Any:
        """Remove All Users.

        Remove all users under a specific admin.

        ``DELETE /api/admin/{username}/users``

        Args:
            username:

        Returns:
            Any
        """
        path = _fmt("/api/admin/{username}/users", {"username": username})
        params = None
        headers = None
        return await self._http.request("delete", path, params=params, headers=headers)

    async def remove_all_users_by_username(self, username: str) -> Any:
        """Remove All Users By Username.

        ``DELETE /api/admin/by-username/{username}/users``

        Args:
            username:

        Returns:
            Any
        """
        path = _fmt("/api/admin/by-username/{username}/users", {"username": username})
        params = None
        headers = None
        return await self._http.request("delete", path, params=params, headers=headers)

    async def remove_all_users_by_id(self, admin_id: int) -> Any:
        """Remove All Users By Id.

        ``DELETE /api/admin/by-id/{admin_id}/users``

        Args:
            admin_id:

        Returns:
            Any
        """
        path = _fmt("/api/admin/by-id/{admin_id}/users", {"admin_id": admin_id})
        params = None
        headers = None
        return await self._http.request("delete", path, params=params, headers=headers)

    async def reset_admin_usage(self, username: str) -> models.AdminDetails:
        """Reset Admin Usage.

        Resets usage of admin.

        ``POST /api/admin/{username}/reset``

        Args:
            username:

        Returns:
            models.AdminDetails
        """
        path = _fmt("/api/admin/{username}/reset", {"username": username})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.AdminDetails.model_validate(data)

    async def reset_admin_usage_by_username(self, username: str) -> models.AdminDetails:
        """Reset Admin Usage By Username.

        ``POST /api/admin/by-username/{username}/reset``

        Args:
            username:

        Returns:
            models.AdminDetails
        """
        path = _fmt("/api/admin/by-username/{username}/reset", {"username": username})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.AdminDetails.model_validate(data)

    async def reset_admin_usage_by_id(self, admin_id: int) -> models.AdminDetails:
        """Reset Admin Usage By Id.

        ``POST /api/admin/by-id/{admin_id}/reset``

        Args:
            admin_id:

        Returns:
            models.AdminDetails
        """
        path = _fmt("/api/admin/by-id/{admin_id}/reset", {"admin_id": admin_id})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.AdminDetails.model_validate(data)

    async def bulk_delete_admins(
        self, *, body: models.BulkAdminSelection | dict[str, Any]
    ) -> models.RemoveAdminsResponse:
        """Bulk Delete Admins.

        Delete selected admins by ID.

        ``POST /api/admins/bulk/delete``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.RemoveAdminsResponse
        """
        path = "/api/admins/bulk/delete"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.RemoveAdminsResponse.model_validate(data)

    async def bulk_reset_admins_usage(
        self, *, body: models.BulkAdminSelection | dict[str, Any]
    ) -> models.BulkAdminsActionResponse:
        """Bulk Reset Admins Usage.

        Reset usage for selected admins by ID.

        ``POST /api/admins/bulk/reset``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkAdminsActionResponse
        """
        path = "/api/admins/bulk/reset"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkAdminsActionResponse.model_validate(data)

    async def bulk_disable_admins(
        self, *, body: models.BulkAdminSelection | dict[str, Any]
    ) -> models.BulkAdminsActionResponse:
        """Bulk Disable Admins.

        Disable selected admins by ID.

        ``POST /api/admins/bulk/disable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkAdminsActionResponse
        """
        path = "/api/admins/bulk/disable"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkAdminsActionResponse.model_validate(data)

    async def bulk_enable_admins(
        self, *, body: models.BulkAdminSelection | dict[str, Any]
    ) -> models.BulkAdminsActionResponse:
        """Bulk Enable Admins.

        Enable selected admins by ID.

        ``POST /api/admins/bulk/enable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkAdminsActionResponse
        """
        path = "/api/admins/bulk/enable"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkAdminsActionResponse.model_validate(data)

    async def bulk_disable_all_active_users(
        self, *, body: models.BulkAdminSelection | dict[str, Any]
    ) -> models.BulkAdminsActionResponse:
        """Bulk Disable All Active Users.

        Disable all active users under selected admins.

        ``POST /api/admins/bulk/users/disable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkAdminsActionResponse
        """
        path = "/api/admins/bulk/users/disable"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkAdminsActionResponse.model_validate(data)

    async def bulk_activate_all_disabled_users(
        self, *, body: models.BulkAdminSelection | dict[str, Any]
    ) -> models.BulkAdminsActionResponse:
        """Bulk Activate All Disabled Users.

        Activate all disabled users under selected admins.

        ``POST /api/admins/bulk/users/activate``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkAdminsActionResponse
        """
        path = "/api/admins/bulk/users/activate"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkAdminsActionResponse.model_validate(data)

    async def bulk_remove_all_users(
        self, *, body: models.BulkAdminSelection | dict[str, Any]
    ) -> models.BulkAdminsActionResponse:
        """Bulk Remove All Users.

        Remove all users under selected admins.

        ``DELETE /api/admins/bulk/users``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkAdminsActionResponse
        """
        path = "/api/admins/bulk/users"
        params = None
        headers = None
        data = await self._http.request("delete", path, params=params, headers=headers, json=_dump(body))
        return models.BulkAdminsActionResponse.model_validate(data)
