"""API Keys endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class ApiKeysResource:
    """API Keys endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def create_api_key(self, *, body: models.APIKeyCreate | dict[str, Any]) -> models.APIKeyCreateResponse:
        """Create Api Key.

        ``POST /api/api_key``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.APIKeyCreateResponse
        """
        path = "/api/api_key"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.APIKeyCreateResponse.model_validate(data)

    async def list_api_keys(
        self,
        *,
        offset: int | None = None,
        limit: int | None = None,
        key_id: int | None = None,
        name: str | None = None,
        status: models.APIKeyStatus | None = None,
    ) -> models.APIKeysResponse:
        """List Api Keys.

        ``GET /api/api_keys``

        Args:
            offset: Query parameter.
            limit: Query parameter.
            key_id: Query parameter.
            name: Query parameter.
            status: Query parameter.

        Returns:
            models.APIKeysResponse
        """
        path = "/api/api_keys"
        params = _clean({"offset": offset, "limit": limit, "key_id": key_id, "name": name, "status": status})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.APIKeysResponse.model_validate(data)

    async def bulk_delete_api_keys(
        self, *, body: models.BulkAPIKeySelection | dict[str, Any]
    ) -> models.RemoveAPIKeysResponse:
        """Bulk Delete Api Keys.

        ``POST /api/api_keys/bulk/delete``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.RemoveAPIKeysResponse
        """
        path = "/api/api_keys/bulk/delete"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.RemoveAPIKeysResponse.model_validate(data)

    async def modify_api_key(self, key_id: int, *, body: models.APIKeyUpdate | dict[str, Any]) -> models.APIKeyResponse:
        """Modify Api Key.

        ``PATCH /api/api_key/{key_id}``

        Args:
            key_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.APIKeyResponse
        """
        path = _fmt("/api/api_key/{key_id}", {"key_id": key_id})
        params = None
        headers = None
        data = await self._http.request("patch", path, params=params, headers=headers, json=_dump(body))
        return models.APIKeyResponse.model_validate(data)

    async def get_api_key(self, key_id: int) -> models.APIKeyResponse:
        """Get Api Key.

        ``GET /api/api_key/{key_id}``

        Args:
            key_id:

        Returns:
            models.APIKeyResponse
        """
        path = _fmt("/api/api_key/{key_id}", {"key_id": key_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.APIKeyResponse.model_validate(data)

    async def remove_api_key(self, key_id: int) -> None:
        """Remove Api Key.

        ``DELETE /api/api_key/{key_id}``

        Args:
            key_id:

        Returns:
            None
        """
        path = _fmt("/api/api_key/{key_id}", {"key_id": key_id})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def revoke_api_key(self, key_id: int) -> models.APIKeyCreateResponse:
        """Revoke Api Key.

        ``POST /api/api_key/{key_id}/revoke``

        Args:
            key_id:

        Returns:
            models.APIKeyCreateResponse
        """
        path = _fmt("/api/api_key/{key_id}/revoke", {"key_id": key_id})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.APIKeyCreateResponse.model_validate(data)
