"""Backups endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class BackupsResource:
    """Backups endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def get_backups(self) -> models.BackupList:
        """Get Backups.

        ``GET /api/backups``

        Returns:
            models.BackupList
        """
        path = "/api/backups"
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.BackupList.model_validate(data)

    async def create_backup_now(self) -> models.BackupInfo:
        """Create Backup Now.

        ``POST /api/backups``

        Returns:
            models.BackupInfo
        """
        path = "/api/backups"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.BackupInfo.model_validate(data)

    async def download_backup(self, name: str) -> bytes:
        """Download Backup.

        ``GET /api/backups/{name}/download``

        Args:
            name:

        Returns:
            bytes
        """
        path = _fmt("/api/backups/{name}/download", {"name": name})
        params = None
        headers = None
        return await self._http.request_bytes("get", path, params=params, headers=headers)

    async def send_backup_telegram(self, name: str) -> None:
        """Send Backup Telegram.

        ``POST /api/backups/{name}/telegram``

        Args:
            name:

        Returns:
            None
        """
        path = _fmt("/api/backups/{name}/telegram", {"name": name})
        params = None
        headers = None
        await self._http.request("post", path, params=params, headers=headers)
        return None

    async def remove_backup(self, name: str) -> None:
        """Remove Backup.

        ``DELETE /api/backups/{name}``

        Args:
            name:

        Returns:
            None
        """
        path = _fmt("/api/backups/{name}", {"name": name})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None
