"""Client Template endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class ClientTemplatesResource:
    """Client Template endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def create_client_template(
        self, *, body: models.ClientTemplateCreate | dict[str, Any]
    ) -> models.ClientTemplateResponse:
        """Create Client Template.

        ``POST /api/client_template``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.ClientTemplateResponse
        """
        path = "/api/client_template"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.ClientTemplateResponse.model_validate(data)

    async def get_client_template(self, template_id: int) -> models.ClientTemplateResponse:
        """Get Client Template.

        ``GET /api/client_template/{template_id}``

        Args:
            template_id:

        Returns:
            models.ClientTemplateResponse
        """
        path = _fmt("/api/client_template/{template_id}", {"template_id": template_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.ClientTemplateResponse.model_validate(data)

    async def modify_client_template(
        self, template_id: int, *, body: models.ClientTemplateModify | dict[str, Any]
    ) -> models.ClientTemplateResponse:
        """Modify Client Template.

        ``PUT /api/client_template/{template_id}``

        Args:
            template_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.ClientTemplateResponse
        """
        path = _fmt("/api/client_template/{template_id}", {"template_id": template_id})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.ClientTemplateResponse.model_validate(data)

    async def remove_client_template(self, template_id: int) -> None:
        """Remove Client Template.

        ``DELETE /api/client_template/{template_id}``

        Args:
            template_id:

        Returns:
            None
        """
        path = _fmt("/api/client_template/{template_id}", {"template_id": template_id})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def get_client_templates(
        self,
        *,
        ids: list[int] | None = None,
        template_type: models.ClientTemplateType | None = None,
        offset: int | None = None,
        limit: int | None = None,
    ) -> models.ClientTemplateResponseList:
        """Get Client Templates.

        ``GET /api/client_templates``

        Args:
            ids: Query parameter.
            template_type: Query parameter.
            offset: Query parameter.
            limit: Query parameter.

        Returns:
            models.ClientTemplateResponseList
        """
        path = "/api/client_templates"
        params = _clean({"ids": ids, "template_type": template_type, "offset": offset, "limit": limit})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.ClientTemplateResponseList.model_validate(data)

    async def get_client_templates_simple(
        self,
        *,
        ids: list[int] | None = None,
        template_type: models.ClientTemplateType | None = None,
        offset: int | None = None,
        limit: int | None = None,
        search: str | None = None,
        sort: str | None = None,
        all: bool | None = None,
    ) -> models.ClientTemplatesSimpleResponse:
        """Get Client Templates Simple.

        ``GET /api/client_templates/simple``

        Args:
            ids: Query parameter.
            template_type: Query parameter.
            offset: Query parameter.
            limit: Query parameter.
            search: Query parameter.
            sort: Query parameter.
            all: Query parameter.

        Returns:
            models.ClientTemplatesSimpleResponse
        """
        path = "/api/client_templates/simple"
        params = _clean(
            {
                "ids": ids,
                "template_type": template_type,
                "offset": offset,
                "limit": limit,
                "search": search,
                "sort": sort,
                "all": all,
            }
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.ClientTemplatesSimpleResponse.model_validate(data)

    async def bulk_delete_client_templates(
        self, *, body: models.BulkClientTemplateSelection | dict[str, Any]
    ) -> models.RemoveClientTemplatesResponse:
        """Bulk Delete Client Templates.

        Delete selected client templates by ID.

        ``POST /api/client_templates/bulk/delete``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.RemoveClientTemplatesResponse
        """
        path = "/api/client_templates/bulk/delete"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.RemoveClientTemplatesResponse.model_validate(data)
