"""Core endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class CoresResource:
    """Core endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def create_core_config(self, *, body: models.CoreCreate | dict[str, Any]) -> models.CoreResponse:
        """Create Core Config.

        Create a new core configuration.

        ``POST /api/core``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.CoreResponse
        """
        path = "/api/core"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.CoreResponse.model_validate(data)

    async def scan_reality_target(
        self, *, body: models.RealityScanRequest | dict[str, Any]
    ) -> models.RealityScanResult:
        """Scan Reality Target.

        ``POST /api/core/reality-scan``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.RealityScanResult
        """
        path = "/api/core/reality-scan"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.RealityScanResult.model_validate(data)

    async def get_core_outbound_stats(
        self, core_id: int, *, start: str | None = None, end: str | None = None, period: models.Period | None = None
    ) -> models.CoreOutboundStats:
        """Get Core Outbound Stats.

        Traffic, latency and availability per outbound on the nodes running this core.

        ``GET /api/core/{core_id}/outbounds/stats``

        Args:
            core_id:
            start: Query parameter.
            end: Query parameter.
            period: Query parameter.

        Returns:
            models.CoreOutboundStats
        """
        path = _fmt("/api/core/{core_id}/outbounds/stats", {"core_id": core_id})
        params = _clean({"start": start, "end": end, "period": period})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.CoreOutboundStats.model_validate(data)

    async def get_core_config(self, core_id: int) -> models.CoreResponse:
        """Get Core Config.

        Get a core configuration by its ID.

        ``GET /api/core/{core_id}``

        Args:
            core_id:

        Returns:
            models.CoreResponse
        """
        path = _fmt("/api/core/{core_id}", {"core_id": core_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.CoreResponse.model_validate(data)

    async def modify_core_config(
        self, core_id: int, *, body: models.CoreCreate | dict[str, Any], restart_nodes: bool
    ) -> models.CoreResponse:
        """Modify Core Config.

        Update an existing core configuration.

        ``PUT /api/core/{core_id}``

        Args:
            core_id:
            body: Request payload (a model instance or a plain dict).
            restart_nodes: Query parameter.

        Returns:
            models.CoreResponse
        """
        path = _fmt("/api/core/{core_id}", {"core_id": core_id})
        params = _clean({"restart_nodes": restart_nodes})
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.CoreResponse.model_validate(data)

    async def delete_core_config(self, core_id: int, *, restart_nodes: bool | None = None) -> None:
        """Delete Core Config.

        Delete a core configuration.

        ``DELETE /api/core/{core_id}``

        Args:
            core_id:
            restart_nodes: Query parameter.

        Returns:
            None
        """
        path = _fmt("/api/core/{core_id}", {"core_id": core_id})
        params = _clean({"restart_nodes": restart_nodes})
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def get_all_cores(
        self, *, ids: list[int] | None = None, offset: int | None = None, limit: int | None = None
    ) -> models.CoreResponseList:
        """Get All Cores.

        Get a list of all core configurations.

        ``GET /api/cores``

        Args:
            ids: Query parameter.
            offset: Query parameter.
            limit: Query parameter.

        Returns:
            models.CoreResponseList
        """
        path = "/api/cores"
        params = _clean({"ids": ids, "offset": offset, "limit": limit})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.CoreResponseList.model_validate(data)

    async def get_cores_simple(
        self,
        *,
        ids: list[int] | None = None,
        offset: int | None = None,
        limit: int | None = None,
        search: str | None = None,
        sort: str | None = None,
        all: bool | None = None,
    ) -> models.CoresSimpleResponse:
        """Get lightweight core list.

        Returns only id and name for cores. Optimized for dropdowns and autocomplete.

        ``GET /api/cores/simple``

        Args:
            ids: Query parameter.
            offset: Query parameter.
            limit: Query parameter.
            search: Query parameter.
            sort: Query parameter.
            all: Query parameter.

        Returns:
            models.CoresSimpleResponse
        """
        path = "/api/cores/simple"
        params = _clean({"ids": ids, "offset": offset, "limit": limit, "search": search, "sort": sort, "all": all})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.CoresSimpleResponse.model_validate(data)

    async def restart_core(self, core_id: int) -> None:
        """Restart Core.

        restart nodes related to the core config

        ``POST /api/core/{core_id}/restart``

        Args:
            core_id:

        Returns:
            None
        """
        path = _fmt("/api/core/{core_id}/restart", {"core_id": core_id})
        params = None
        headers = None
        await self._http.request("post", path, params=params, headers=headers)
        return None

    async def bulk_delete_cores(self, *, body: models.BulkCoreSelection | dict[str, Any]) -> models.RemoveCoresResponse:
        """Bulk Delete Cores.

        Delete selected cores by ID.

        ``POST /api/cores/bulk/delete``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.RemoveCoresResponse
        """
        path = "/api/cores/bulk/delete"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.RemoveCoresResponse.model_validate(data)
