"""Groups endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class GroupsResource:
    """Groups endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def create_group(self, *, body: models.GroupCreate | dict[str, Any]) -> models.GroupResponse:
        """Create a new group.

        Creates a new group in the system. Only authorized administrators can create groups.

        ``POST /api/group``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.GroupResponse
        """
        path = "/api/group"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.GroupResponse.model_validate(data)

    async def get_all_groups(
        self, *, ids: list[int] | None = None, offset: int | None = None, limit: int | None = None
    ) -> models.GroupsResponse:
        """List all groups.

        Retrieves a paginated list of all groups in the system. Requires admin authentication.

        ``GET /api/groups``

        Args:
            ids: Query parameter.
            offset: Query parameter.
            limit: Query parameter.

        Returns:
            models.GroupsResponse
        """
        path = "/api/groups"
        params = _clean({"ids": ids, "offset": offset, "limit": limit})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.GroupsResponse.model_validate(data)

    async def get_groups_simple(
        self,
        *,
        ids: list[int] | None = None,
        offset: int | None = None,
        limit: int | None = None,
        search: str | None = None,
        sort: str | None = None,
        all: bool | None = None,
    ) -> models.GroupsSimpleResponse:
        """Get lightweight group list.

        Returns only id and name for groups. Optimized for dropdowns and autocomplete.

        ``GET /api/groups/simple``

        Args:
            ids: Query parameter.
            offset: Query parameter.
            limit: Query parameter.
            search: Query parameter.
            sort: Query parameter.
            all: Query parameter.

        Returns:
            models.GroupsSimpleResponse
        """
        path = "/api/groups/simple"
        params = _clean({"ids": ids, "offset": offset, "limit": limit, "search": search, "sort": sort, "all": all})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.GroupsSimpleResponse.model_validate(data)

    async def get_group(self, group_id: int) -> models.GroupResponse:
        """Get group details.

        Retrieves detailed information about a specific group by its ID.

        ``GET /api/group/{group_id}``

        Args:
            group_id:

        Returns:
            models.GroupResponse
        """
        path = _fmt("/api/group/{group_id}", {"group_id": group_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.GroupResponse.model_validate(data)

    async def modify_group(self, group_id: int, *, body: models.GroupModify | dict[str, Any]) -> models.GroupResponse:
        """Modify group.

        Updates an existing group's information. Only authorized administrators can modify groups.

        ``PUT /api/group/{group_id}``

        Args:
            group_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.GroupResponse
        """
        path = _fmt("/api/group/{group_id}", {"group_id": group_id})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.GroupResponse.model_validate(data)

    async def remove_group(self, group_id: int) -> None:
        """Remove group.

        Deletes a group from the system. Only authorized administrators can delete groups.

        ``DELETE /api/group/{group_id}``

        Args:
            group_id:

        Returns:
            None
        """
        path = _fmt("/api/group/{group_id}", {"group_id": group_id})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def bulk_add_groups_to_users(self, *, body: models.BulkGroup | dict[str, Any]) -> Any:
        """Bulk add groups to users.

        Bulk assign groups to multiple users, users under specific admins, or all users.

        - **group_ids**: List of group IDs to add (required)
        - **users**: Optional list of user IDs to assign the groups to
        - **admins**: Optional list of admin IDs — their users will be targeted

        Notes:
        - If neither 'users' nor 'admins' are provided, groups will be added to *all users*
        - Existing user-group associations will be ignored (no duplication)
        - Returns list of affected users (those who received new group associations)

        ``POST /api/groups/bulk/add``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            Any
        """
        path = "/api/groups/bulk/add"
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers, json=_dump(body))

    async def bulk_remove_users_from_groups(self, *, body: models.BulkGroup | dict[str, Any]) -> Any:
        """Bulk remove groups from users.

        Bulk remove groups from multiple users, users under specific admins, or all users.

        - **group_ids**: List of group IDs to remove (required)
        - **users**: Optional list of user IDs to remove the groups from
        - **admins**: Optional list of admin IDs — their users will be targeted

        Notes:
        - If neither 'users' nor 'admins' are provided, groups will be removed from *all users*
        - Only existing user-group associations will be removed
        - Returns list of affected users (those who had groups removed)

        ``POST /api/groups/bulk/remove``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            Any
        """
        path = "/api/groups/bulk/remove"
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers, json=_dump(body))

    async def bulk_delete_groups(
        self, *, body: models.BulkGroupSelection | dict[str, Any]
    ) -> models.RemoveGroupsResponse:
        """Bulk Delete Groups.

        Delete selected groups by ID.

        ``POST /api/groups/bulk/delete``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.RemoveGroupsResponse
        """
        path = "/api/groups/bulk/delete"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.RemoveGroupsResponse.model_validate(data)

    async def bulk_disable_groups(
        self, *, body: models.BulkGroupSelection | dict[str, Any]
    ) -> models.BulkGroupsActionResponse:
        """Bulk Disable Groups.

        Disable selected groups by ID.

        ``POST /api/groups/bulk/disable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkGroupsActionResponse
        """
        path = "/api/groups/bulk/disable"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkGroupsActionResponse.model_validate(data)

    async def bulk_enable_groups(
        self, *, body: models.BulkGroupSelection | dict[str, Any]
    ) -> models.BulkGroupsActionResponse:
        """Bulk Enable Groups.

        Enable selected groups by ID.

        ``POST /api/groups/bulk/enable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkGroupsActionResponse
        """
        path = "/api/groups/bulk/enable"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkGroupsActionResponse.model_validate(data)
