"""Host endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class HostsResource:
    """Host endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def get_host(self, host_id: int) -> models.BaseHost:
        """Get Host.

        get host by **id**

        ``GET /api/host/{host_id}``

        Args:
            host_id:

        Returns:
            models.BaseHost
        """
        path = _fmt("/api/host/{host_id}", {"host_id": host_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.BaseHost.model_validate(data)

    async def modify_host(self, host_id: int, *, body: models.CreateHost | dict[str, Any]) -> models.BaseHost:
        """Modify Host.

        modify host by **id**

        **inbound_tag** must be available in one of the configured cores

        ``PUT /api/host/{host_id}``

        Args:
            host_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BaseHost
        """
        path = _fmt("/api/host/{host_id}", {"host_id": host_id})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.BaseHost.model_validate(data)

    async def remove_host(self, host_id: int) -> None:
        """Remove Host.

        remove host by **id**

        ``DELETE /api/host/{host_id}``

        Args:
            host_id:

        Returns:
            None
        """
        path = _fmt("/api/host/{host_id}", {"host_id": host_id})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def get_hosts(
        self, *, ids: list[int] | None = None, offset: int | None = None, limit: int | None = None
    ) -> list[models.BaseHost]:
        """Get Hosts.

        Get proxy hosts.

        ``GET /api/hosts``

        Args:
            ids: Query parameter.
            offset: Query parameter.
            limit: Query parameter.

        Returns:
            list[models.BaseHost]
        """
        path = "/api/hosts"
        params = _clean({"ids": ids, "offset": offset, "limit": limit})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return [models.BaseHost.model_validate(x) for x in data]

    async def modify_hosts(self, *, body: list[models.CreateHost]) -> list[models.BaseHost]:
        """Modify Hosts.

        Modify proxy hosts and update the configuration.

        ``PUT /api/hosts``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            list[models.BaseHost]
        """
        path = "/api/hosts"
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return [models.BaseHost.model_validate(x) for x in data]

    async def create_host(self, *, body: models.CreateHost | dict[str, Any]) -> models.BaseHost:
        """Create Host.

        create a new host

        **inbound_tag** must be available in one of the configured cores

        ``POST /api/host/``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BaseHost
        """
        path = "/api/host/"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BaseHost.model_validate(data)

    async def bulk_delete_hosts(self, *, body: models.BulkHostSelection | dict[str, Any]) -> models.RemoveHostsResponse:
        """Bulk Delete Hosts.

        Delete selected hosts by ID.

        ``POST /api/hosts/bulk/delete``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.RemoveHostsResponse
        """
        path = "/api/hosts/bulk/delete"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.RemoveHostsResponse.model_validate(data)

    async def bulk_disable_hosts(
        self, *, body: models.BulkHostSelection | dict[str, Any]
    ) -> models.BulkHostsActionResponse:
        """Bulk Disable Hosts.

        Disable selected hosts by ID.

        ``POST /api/hosts/bulk/disable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkHostsActionResponse
        """
        path = "/api/hosts/bulk/disable"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkHostsActionResponse.model_validate(data)

    async def bulk_enable_hosts(
        self, *, body: models.BulkHostSelection | dict[str, Any]
    ) -> models.BulkHostsActionResponse:
        """Bulk Enable Hosts.

        Enable selected hosts by ID.

        ``POST /api/hosts/bulk/enable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkHostsActionResponse
        """
        path = "/api/hosts/bulk/enable"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkHostsActionResponse.model_validate(data)
