"""User HWID endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class HwidsResource:
    """User HWID endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def get_user_hwids(self, user_id: int) -> models.UserHWIDListResponse:
        """Get User Hwids.

        Get user's registered hardware IDs

        ``GET /api/user/{user_id}/hwids``

        Args:
            user_id:

        Returns:
            models.UserHWIDListResponse
        """
        path = _fmt("/api/user/{user_id}/hwids", {"user_id": user_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserHWIDListResponse.model_validate(data)

    async def delete_user_hwid(self, user_id: int, hwid: str) -> Any:
        """Delete User Hwid.

        Delete a specific hardware ID from user

        ``DELETE /api/user/{user_id}/hwids/{hwid}``

        Args:
            user_id:
            hwid:

        Returns:
            Any
        """
        path = _fmt("/api/user/{user_id}/hwids/{hwid}", {"user_id": user_id, "hwid": hwid})
        params = None
        headers = None
        return await self._http.request("delete", path, params=params, headers=headers)

    async def reset_user_hwids(self, user_id: int) -> Any:
        """Reset User Hwids.

        Delete all hardware IDs for user

        ``POST /api/user/{user_id}/hwids/reset``

        Args:
            user_id:

        Returns:
            Any
        """
        path = _fmt("/api/user/{user_id}/hwids/reset", {"user_id": user_id})
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers)
