"""Miscellaneous endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class MiscResource:
    """Miscellaneous endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def base(self) -> str:
        """Base.

        ``GET /``

        Returns:
            str
        """
        path = "/"
        params = None
        headers = None
        return await self._http.request("get", path, params=params, headers=headers)

    async def health(self) -> dict[str, Any]:
        """Health.

        ``GET /health``

        Returns:
            dict[str, Any]
        """
        path = "/health"
        params = None
        headers = None
        return await self._http.request("get", path, params=params, headers=headers)
