"""Node endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class NodesResource:
    """Node endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def get_node_settings(self) -> models.NodeSettings:
        """Get Node Settings.

        Retrieve the current node settings.

        ``GET /api/node/settings``

        Returns:
            models.NodeSettings
        """
        path = "/api/node/settings"
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.NodeSettings.model_validate(data)

    async def get_core_releases(self, *, core: str) -> models.CoreReleasesResponse:
        """Get Core Releases.

        Releases a node can install for a core: xray, hysteria2, singbox or amneziawg.

        ``GET /api/node/core_releases``

        Args:
            core: Query parameter.

        Returns:
            models.CoreReleasesResponse
        """
        path = "/api/node/core_releases"
        params = _clean({"core": core})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.CoreReleasesResponse.model_validate(data)

    async def get_usage(
        self,
        *,
        period: models.Period | None = None,
        node_id: int | None = None,
        group_by_node: bool | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
    ) -> models.NodeUsageStatsList:
        """Get Usage.

        Retrieve usage statistics for nodes within a specified date range.

        ``GET /api/node/usage``

        Args:
            period: Query parameter.
            node_id: Query parameter.
            group_by_node: Query parameter.
            start: Query parameter.
            end: Query parameter.

        Returns:
            models.NodeUsageStatsList
        """
        path = "/api/node/usage"
        params = _clean(
            {"period": period, "node_id": node_id, "group_by_node": group_by_node, "start": start, "end": end}
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.NodeUsageStatsList.model_validate(data)

    async def get_user_count_metric(
        self,
        metric: models.UserCountMetric | str,
        *,
        period: models.Period | None = None,
        node_id: int | None = None,
        group_by_node: bool | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
    ) -> models.UserCountMetricStatsList:
        """Get User Count Metric.

        Retrieve one user activity/status count metric from node user usage rows.

        ``GET /api/node/user_counts/{metric}``

        Args:
            metric:
            period: Query parameter.
            node_id: Query parameter.
            group_by_node: Query parameter.
            start: Query parameter.
            end: Query parameter.

        Returns:
            models.UserCountMetricStatsList
        """
        path = _fmt("/api/node/user_counts/{metric}", {"metric": metric})
        params = _clean(
            {"period": period, "node_id": node_id, "group_by_node": group_by_node, "start": start, "end": end}
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserCountMetricStatsList.model_validate(data)

    async def get_nodes(
        self,
        *,
        core_id: int | None = None,
        offset: int | None = None,
        limit: int | None = None,
        ids: list[int] | None = None,
        status: models.NodeStatus | list[models.NodeStatus] | None = None,
        enabled: bool | None = None,
        search: str | None = None,
    ) -> models.NodesResponse:
        """Get Nodes.

        Retrieve a list of all nodes. Accessible only to authorized admins.

        ``GET /api/nodes``

        Args:
            core_id: Query parameter.
            offset: Query parameter.
            limit: Query parameter.
            ids: Query parameter.
            status: Query parameter.
            enabled: Query parameter.
            search: Query parameter.

        Returns:
            models.NodesResponse
        """
        path = "/api/nodes"
        params = _clean(
            {
                "core_id": core_id,
                "offset": offset,
                "limit": limit,
                "ids": ids,
                "status": status,
                "enabled": enabled,
                "search": search,
            }
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.NodesResponse.model_validate(data)

    async def get_nodes_simple(
        self,
        *,
        ids: list[int] | None = None,
        offset: int | None = None,
        limit: int | None = None,
        search: str | None = None,
        sort: str | None = None,
        all: bool | None = None,
    ) -> models.NodesSimpleResponse:
        """Get lightweight node list.

        Returns only id and name for nodes. Optimized for dropdowns and autocomplete.

        ``GET /api/nodes/simple``

        Args:
            ids: Query parameter.
            offset: Query parameter.
            limit: Query parameter.
            search: Query parameter.
            sort: Query parameter.
            all: Query parameter.

        Returns:
            models.NodesSimpleResponse
        """
        path = "/api/nodes/simple"
        params = _clean({"ids": ids, "offset": offset, "limit": limit, "search": search, "sort": sort, "all": all})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.NodesSimpleResponse.model_validate(data)

    async def reconnect_all_node(self, *, core_id: int | None = None) -> Any:
        """Reconnect All Node.

        Trigger reconnection for all nodes or a specific core.

        ``POST /api/nodes/reconnect``

        Args:
            core_id: Query parameter.

        Returns:
            Any
        """
        path = "/api/nodes/reconnect"
        params = _clean({"core_id": core_id})
        headers = None
        return await self._http.request("post", path, params=params, headers=headers)

    async def create_node(self, *, body: models.NodeCreate | dict[str, Any]) -> models.NodeResponse:
        """Create Node.

        Create a new node to the database.

        ``POST /api/node``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.NodeResponse
        """
        path = "/api/node"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.NodeResponse.model_validate(data)

    async def get_node(self, node_id: int) -> models.NodeResponse:
        """Get Node.

        Retrieve details of a specific node by its ID.

        ``GET /api/node/{node_id}``

        Args:
            node_id:

        Returns:
            models.NodeResponse
        """
        path = _fmt("/api/node/{node_id}", {"node_id": node_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.NodeResponse.model_validate(data)

    async def modify_node(self, node_id: int, *, body: models.NodeModify | dict[str, Any]) -> models.NodeResponse:
        """Modify Node.

        Modify a node's details. Only accessible to authorized admins.

        ``PUT /api/node/{node_id}``

        Args:
            node_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.NodeResponse
        """
        path = _fmt("/api/node/{node_id}", {"node_id": node_id})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.NodeResponse.model_validate(data)

    async def remove_node(self, node_id: int) -> None:
        """Remove Node.

        Remove a node and remove it from xray in the background.

        ``DELETE /api/node/{node_id}``

        Args:
            node_id:

        Returns:
            None
        """
        path = _fmt("/api/node/{node_id}", {"node_id": node_id})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def update_node(self, node_id: int) -> Any:
        """Update Node.

        ``POST /api/node/{node_id}/update``

        Args:
            node_id:

        Returns:
            Any
        """
        path = _fmt("/api/node/{node_id}/update", {"node_id": node_id})
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers)

    async def update_core(self, node_id: int, *, body: models.NodeCoreUpdate | dict[str, Any]) -> Any:
        """Update Core.

        ``POST /api/node/{node_id}/core_update``

        Args:
            node_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            Any
        """
        path = _fmt("/api/node/{node_id}/core_update", {"node_id": node_id})
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers, json=_dump(body))

    async def update_geofiles(self, node_id: int, *, body: models.NodeGeoFilesUpdate | dict[str, Any]) -> Any:
        """Update Geofiles.

        ``POST /api/node/{node_id}/geofiles``

        Args:
            node_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            Any
        """
        path = _fmt("/api/node/{node_id}/geofiles", {"node_id": node_id})
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers, json=_dump(body))

    async def reset_node_usage(self, node_id: int) -> models.NodeResponse:
        """Reset Node Usage.

        Reset node traffic usage (uplink and downlink).
        Creates a log entry in node_usage_reset_logs table.
        Only accessible to authorized admins.

        ``POST /api/node/{node_id}/reset``

        Args:
            node_id:

        Returns:
            models.NodeResponse
        """
        path = _fmt("/api/node/{node_id}/reset", {"node_id": node_id})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.NodeResponse.model_validate(data)

    async def reconnect_node(self, node_id: int) -> Any:
        """Reconnect Node.

        Trigger a reconnection for the specified node. Only accessible to authorized admins.

        ``POST /api/node/{node_id}/reconnect``

        Args:
            node_id:

        Returns:
            Any
        """
        path = _fmt("/api/node/{node_id}/reconnect", {"node_id": node_id})
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers)

    async def sync_node(self, node_id: int, *, flush_users: bool | None = None) -> Any:
        """Sync Node.

        ``PUT /api/node/{node_id}/sync``

        Args:
            node_id:
            flush_users: Query parameter.

        Returns:
            Any
        """
        path = _fmt("/api/node/{node_id}/sync", {"node_id": node_id})
        params = _clean({"flush_users": flush_users})
        headers = None
        return await self._http.request("put", path, params=params, headers=headers)

    async def node_logs(self, node_id: int) -> AsyncIterator[str]:
        """Node Logs.

        Stream logs for a specific node as Server-Sent Events.

        ``GET /api/node/{node_id}/logs``

        Args:
            node_id:

        Returns:
            AsyncIterator[str]
        """
        path = _fmt("/api/node/{node_id}/logs", {"node_id": node_id})
        params = None
        headers = None
        async for line in self._http.stream_sse("get", path, params=params, headers=headers):
            yield line

    async def get_node_stats_periodic(
        self,
        node_id: int,
        *,
        period: models.Period | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
    ) -> models.NodeStatsList:
        """Get Node Stats Periodic.

        ``GET /api/node/{node_id}/stats``

        Args:
            node_id:
            period: Query parameter.
            start: Query parameter.
            end: Query parameter.

        Returns:
            models.NodeStatsList
        """
        path = _fmt("/api/node/{node_id}/stats", {"node_id": node_id})
        params = _clean({"period": period, "start": start, "end": end})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.NodeStatsList.model_validate(data)

    async def realtime_node_stats(self, node_id: int) -> models.NodeRealtimeStats:
        """Realtime Node Stats.

        Retrieve node real-time statistics.

        ``GET /api/node/{node_id}/realtime_stats``

        Args:
            node_id:

        Returns:
            models.NodeRealtimeStats
        """
        path = _fmt("/api/node/{node_id}/realtime_stats", {"node_id": node_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.NodeRealtimeStats.model_validate(data)

    async def node_outbounds_latency(
        self, node_id: int, *, name: str | None = None, timeout: int | None = None, fresh: bool | None = None
    ) -> models.NodeOutboundsLatencyResponse:
        """Node Outbounds Latency.

        Outbound latency of a node; fresh=true waits for a probe taken after the call.

        ``GET /api/node/{node_id}/outbounds_latency``

        Args:
            node_id:
            name: Query parameter.
            timeout: Query parameter.
            fresh: Query parameter.

        Returns:
            models.NodeOutboundsLatencyResponse
        """
        path = _fmt("/api/node/{node_id}/outbounds_latency", {"node_id": node_id})
        params = _clean({"name": name, "timeout": timeout, "fresh": fresh})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.NodeOutboundsLatencyResponse.model_validate(data)

    async def node_routing_rules(self, node_id: int) -> models.LiveRoutingRules:
        """Node Routing Rules.

        Routing rules the node's Xray router holds right now.

        ``GET /api/node/{node_id}/routing/rules``

        Args:
            node_id:

        Returns:
            models.LiveRoutingRules
        """
        path = _fmt("/api/node/{node_id}/routing/rules", {"node_id": node_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.LiveRoutingRules.model_validate(data)

    async def node_add_routing_rule(self, node_id: int, *, body: models.LiveRoutingRuleAdd | dict[str, Any]) -> None:
        """Node Add Routing Rule.

        Add a routing rule to the running router (lost on restart).

        ``POST /api/node/{node_id}/routing/rules``

        Args:
            node_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            None
        """
        path = _fmt("/api/node/{node_id}/routing/rules", {"node_id": node_id})
        params = None
        headers = None
        await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return None

    async def node_test_route(
        self, node_id: int, *, body: models.RouteTestRequest | dict[str, Any]
    ) -> models.RouteTestResult:
        """Node Test Route.

        Ask the node's router which outbound a connection would take.

        ``POST /api/node/{node_id}/routing/test``

        Args:
            node_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.RouteTestResult
        """
        path = _fmt("/api/node/{node_id}/routing/test", {"node_id": node_id})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.RouteTestResult.model_validate(data)

    async def node_remove_routing_rule(self, node_id: int, rule_tag: str) -> None:
        """Node Remove Routing Rule.

        Remove a routing rule from the running router by its ruleTag.

        ``DELETE /api/node/{node_id}/routing/rules/{rule_tag}``

        Args:
            node_id:
            rule_tag:

        Returns:
            None
        """
        path = _fmt("/api/node/{node_id}/routing/rules/{rule_tag}", {"node_id": node_id, "rule_tag": rule_tag})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def node_balancer_info(self, node_id: int, tag: str) -> models.BalancerInfo:
        """Node Balancer Info.

        ``GET /api/node/{node_id}/routing/balancer/{tag}``

        Args:
            node_id:
            tag:

        Returns:
            models.BalancerInfo
        """
        path = _fmt("/api/node/{node_id}/routing/balancer/{tag}", {"node_id": node_id, "tag": tag})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.BalancerInfo.model_validate(data)

    async def node_override_balancer(
        self, node_id: int, tag: str, *, body: models.BalancerOverride | dict[str, Any]
    ) -> None:
        """Node Override Balancer.

        ``PUT /api/node/{node_id}/routing/balancer/{tag}``

        Args:
            node_id:
            tag:
            body: Request payload (a model instance or a plain dict).

        Returns:
            None
        """
        path = _fmt("/api/node/{node_id}/routing/balancer/{tag}", {"node_id": node_id, "tag": tag})
        params = None
        headers = None
        await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return None

    async def nodes_online_counts(self) -> models.NodesOnlineCounts:
        """Nodes Online Counts.

        Users online per node right now, from the panel's last poll of every node (about every 10 s).

        ``GET /api/nodes/online_counts``

        Returns:
            models.NodesOnlineCounts
        """
        path = "/api/nodes/online_counts"
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.NodesOnlineCounts.model_validate(data)

    async def nodes_latency(self) -> models.ServerLatencyList:
        """Nodes Latency.

        Latest TCP-connect round trips between node servers and from the panel, for the latency map.

        A server is a node address; ``source`` null means the panel measured. Rounds run every ``interval`` seconds.

        ``GET /api/nodes/latency``

        Returns:
            models.ServerLatencyList
        """
        path = "/api/nodes/latency"
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.ServerLatencyList.model_validate(data)

    async def refresh_nodes_latency(self) -> models.ServerLatencyList:
        """Refresh Nodes Latency.

        Measure the round trips now (skipped when a round finished in the last 30 seconds) and return them.

        ``POST /api/nodes/latency/refresh``

        Returns:
            models.ServerLatencyList
        """
        path = "/api/nodes/latency/refresh"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.ServerLatencyList.model_validate(data)

    async def realtime_nodes_stats(self) -> dict[str, Any]:
        """Realtime Nodes Stats.

        Retrieve nodes real-time statistics.

        ``GET /api/nodes/realtime_stats``

        Returns:
            dict[str, Any]
        """
        path = "/api/nodes/realtime_stats"
        params = None
        headers = None
        return await self._http.request("get", path, params=params, headers=headers)

    async def user_online_ip_list_all_nodes(self, user_id: int) -> models.UserIPListAll:
        """User Online Ip List All Nodes.

        Retrieve user ips from all nodes.

        ``GET /api/node/online_stats/{user_id}/ip``

        Args:
            user_id:

        Returns:
            models.UserIPListAll
        """
        path = _fmt("/api/node/online_stats/{user_id}/ip", {"user_id": user_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserIPListAll.model_validate(data)

    async def user_online_stats(self, node_id: int, user_id: int) -> dict[str, Any]:
        """User Online Stats.

        Retrieve user online stats by node.

        ``GET /api/node/{node_id}/online_stats/{user_id}``

        Args:
            node_id:
            user_id:

        Returns:
            dict[str, Any]
        """
        path = _fmt("/api/node/{node_id}/online_stats/{user_id}", {"node_id": node_id, "user_id": user_id})
        params = None
        headers = None
        return await self._http.request("get", path, params=params, headers=headers)

    async def user_online_ip_list(self, node_id: int, user_id: int) -> models.UserIPList:
        """User Online Ip List.

        Retrieve user ips by node.

        ``GET /api/node/{node_id}/online_stats/{user_id}/ip``

        Args:
            node_id:
            user_id:

        Returns:
            models.UserIPList
        """
        path = _fmt("/api/node/{node_id}/online_stats/{user_id}/ip", {"node_id": node_id, "user_id": user_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserIPList.model_validate(data)

    async def clear_usage_data(
        self, table: models.UsageTable | str, *, start: datetime | None = None, end: datetime | None = None
    ) -> Any:
        """Clear usage data from a specified table.

        Deletes **all rows** from the selected usage data table. Use with caution.

        Allowed tables:
            - `node_user_usages`: Deletes user-specific node usage traffic records.
            - `node_usages`: Deletes node-level aggregated traffic (uplink/downlink) records.

        **Optional filters:**
            - `start`: ISO 8601 timestamp to filter from (inclusive)
            - `end`: ISO 8601 timestamp to filter to (exclusive)

        ⚠️ This operation is irreversible. Ensure correct usage in production environments.

        ``DELETE /api/nodes/clear_usage_data/{table}``

        Args:
            table:
            start: Query parameter.
            end: Query parameter.

        Returns:
            Any
        """
        path = _fmt("/api/nodes/clear_usage_data/{table}", {"table": table})
        params = _clean({"start": start, "end": end})
        headers = None
        return await self._http.request("delete", path, params=params, headers=headers)

    async def bulk_delete_nodes(self, *, body: models.BulkNodeSelection | dict[str, Any]) -> models.RemoveNodesResponse:
        """Bulk Delete Nodes.

        Delete selected nodes by ID.

        ``POST /api/nodes/bulk/delete``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.RemoveNodesResponse
        """
        path = "/api/nodes/bulk/delete"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.RemoveNodesResponse.model_validate(data)

    async def bulk_disable_nodes(
        self, *, body: models.BulkNodeSelection | dict[str, Any]
    ) -> models.BulkNodesActionResponse:
        """Bulk Disable Nodes.

        Disable selected nodes by ID.

        ``POST /api/nodes/bulk/disable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkNodesActionResponse
        """
        path = "/api/nodes/bulk/disable"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkNodesActionResponse.model_validate(data)

    async def bulk_enable_nodes(
        self, *, body: models.BulkNodeSelection | dict[str, Any]
    ) -> models.BulkNodesActionResponse:
        """Bulk Enable Nodes.

        Enable selected nodes by ID.

        ``POST /api/nodes/bulk/enable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkNodesActionResponse
        """
        path = "/api/nodes/bulk/enable"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkNodesActionResponse.model_validate(data)

    async def bulk_reset_nodes_usage(
        self, *, body: models.BulkNodeSelection | dict[str, Any]
    ) -> models.BulkNodesActionResponse:
        """Bulk Reset Nodes Usage.

        Reset usage for selected nodes by ID.

        ``POST /api/nodes/bulk/reset``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkNodesActionResponse
        """
        path = "/api/nodes/bulk/reset"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkNodesActionResponse.model_validate(data)

    async def bulk_reconnect_nodes(
        self, *, body: models.BulkNodeSelection | dict[str, Any]
    ) -> models.BulkNodesActionResponse:
        """Bulk Reconnect Nodes.

        Reconnect selected nodes by ID.

        ``POST /api/nodes/bulk/reconnect``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkNodesActionResponse
        """
        path = "/api/nodes/bulk/reconnect"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkNodesActionResponse.model_validate(data)

    async def bulk_update_nodes(
        self, *, body: models.BulkNodeSelection | dict[str, Any]
    ) -> models.BulkNodesActionResponse:
        """Bulk Update Nodes.

        Update selected nodes by ID.

        ``POST /api/nodes/bulk/update``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkNodesActionResponse
        """
        path = "/api/nodes/bulk/update"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkNodesActionResponse.model_validate(data)

    async def create_install(self, *, body: models.InstallCreate | dict[str, Any]) -> models.InstallResponse:
        """Create Install.

        Start an install run and return its one-time token (shown only here).

        ``POST /api/node/install``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.InstallResponse
        """
        path = "/api/node/install"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.InstallResponse.model_validate(data)

    async def get_install(self, install_id: int) -> models.InstallResponse:
        """Get Install.

        Live progress of an install run.

        ``GET /api/node/install/{install_id}``

        Args:
            install_id:

        Returns:
            models.InstallResponse
        """
        path = _fmt("/api/node/install/{install_id}", {"install_id": install_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.InstallResponse.model_validate(data)
