"""Push endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class PushResource:
    """Push endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def push_subscribers(self) -> models.PushSubscribers:
        """Push Subscribers.

        Which users have notifications switched on, and on how many devices.

        ``GET /api/push/subscribers``

        Returns:
            models.PushSubscribers
        """
        path = "/api/push/subscribers"
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.PushSubscribers.model_validate(data)

    async def push_send(self, *, body: models.PushSend | dict[str, Any]) -> models.PushResult:
        """Push Send.

        Send one notification to the chosen users' devices.

        ``POST /api/push/send``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.PushResult
        """
        path = "/api/push/send"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.PushResult.model_validate(data)
