"""Settings endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class SettingsResource:
    """Settings endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def get_settings(self) -> models.SettingsSchema:
        """Get Settings.

        ``GET /api/settings``

        Returns:
            models.SettingsSchema
        """
        path = "/api/settings"
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.SettingsSchema.model_validate(data)

    async def modify_settings(self, *, body: models.SettingsSchema | dict[str, Any]) -> models.SettingsSchema:
        """Modify Settings.

        ``PUT /api/settings``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.SettingsSchema
        """
        path = "/api/settings"
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.SettingsSchema.model_validate(data)

    async def get_general_settings(self) -> models.General:
        """Get General Settings.

        ``GET /api/settings/general``

        Returns:
            models.General
        """
        path = "/api/settings/general"
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.General.model_validate(data)

    async def get_timezone(self) -> dict[str, Any]:
        """Get Timezone.

        The panel timezone; every admin needs it to render times, not only settings readers.

        ``GET /api/settings/timezone``

        Returns:
            dict[str, Any]
        """
        path = "/api/settings/timezone"
        params = None
        headers = None
        return await self._http.request("get", path, params=params, headers=headers)
