"""Setup endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class SetupResource:
    """Setup endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def setup_status(self) -> dict[str, Any]:
        """Setup Status.

        Whether the panel still needs its owner account; the sign-in page offers setup only then.

        ``GET /api/setup/status``

        Returns:
            dict[str, Any]
        """
        path = "/api/setup/status"
        params = None
        headers = None
        return await self._http.request("get", path, params=params, headers=headers)

    async def create_owner(self, *, body: models.OwnerCreateRequest | dict[str, Any]) -> models.AdminDetails:
        """Create Owner.

        Create the owner admin using a one-time temp key.

        ``POST /api/setup/owner``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.AdminDetails
        """
        path = "/api/setup/owner"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.AdminDetails.model_validate(data)

    async def reset_owner_password(self, *, body: models.OwnerResetRequest | dict[str, Any]) -> models.AdminDetails:
        """Reset Owner Password.

        Reset the owner admin's password using a one-time temp key.

        ``PATCH /api/setup/owner``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.AdminDetails
        """
        path = "/api/setup/owner"
        params = None
        headers = None
        data = await self._http.request("patch", path, params=params, headers=headers, json=_dump(body))
        return models.AdminDetails.model_validate(data)

    async def delete_owner(self, *, key: str) -> None:
        """Delete Owner.

        Delete the owner admin using a one-time temp key.

        ``DELETE /api/setup/owner``

        Args:
            key: One-time temp key for deleting the owner admin Query parameter.

        Returns:
            None
        """
        path = "/api/setup/owner"
        params = _clean({"key": key})
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def upgrade_owner(self, *, body: models.OwnerUpgradeRequest | dict[str, Any]) -> models.AdminDetails:
        """Upgrade Owner.

        Upgrade an existing admin to owner using a one-time temp key.

        ``POST /api/setup/owner/upgrade``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.AdminDetails
        """
        path = "/api/setup/owner/upgrade"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.AdminDetails.model_validate(data)
