"""Subscription endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class SubscriptionResource:
    """Subscription endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def user_subscription(
        self,
        token: str,
        *,
        user_agent: str | None = None,
        x_hwid: str | None = None,
        x_device_os: str | None = None,
        x_ver_os: str | None = None,
        x_device_model: str | None = None,
    ) -> Any:
        """User Subscription.

        Provides a subscription link based on the user agent (Clash, V2Ray, etc.).

        ``GET /sub/{token}/``

        Args:
            token:
            user_agent: Header ``user-agent``.
            x_hwid: Header ``X-HWID``.
            x_device_os: Header ``X-Device-OS``.
            x_ver_os: Header ``X-Ver-OS``.
            x_device_model: Header ``X-Device-Model``.

        Returns:
            Any
        """
        path = _fmt("/sub/{token}/", {"token": token})
        params = None
        headers = _clean(
            {
                "user-agent": user_agent,
                "X-HWID": x_hwid,
                "X-Device-OS": x_device_os,
                "X-Ver-OS": x_ver_os,
                "X-Device-Model": x_device_model,
            }
        )
        return await self._http.request("get", path, params=params, headers=headers)

    async def user_subscription_headers(self, token: str, *, user_agent: str | None = None) -> Any:
        """User Subscription Headers.

        Provides subscription headers without response body.

        ``HEAD /sub/{token}/``

        Args:
            token:
            user_agent: Header ``user-agent``.

        Returns:
            Any
        """
        path = _fmt("/sub/{token}/", {"token": token})
        params = None
        headers = _clean({"user-agent": user_agent})
        return await self._http.request("head", path, params=params, headers=headers)

    async def user_subscription_info(self, token: str) -> models.SubscriptionUserResponse:
        """User Subscription Info.

        Retrieves detailed information about the user's subscription.

        ``GET /sub/{token}/info``

        Args:
            token:

        Returns:
            models.SubscriptionUserResponse
        """
        path = _fmt("/sub/{token}/info", {"token": token})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.SubscriptionUserResponse.model_validate(data)

    async def user_subscription_raw(self, token: str) -> Any:
        """User Subscription Raw.

        ``GET /sub/{token}/raw``

        Args:
            token:

        Returns:
            Any
        """
        path = _fmt("/sub/{token}/raw", {"token": token})
        params = None
        headers = None
        return await self._http.request("get", path, params=params, headers=headers)

    async def user_subscription_apps(self, token: str) -> list[models.Application]:
        """User Subscription Apps.

        Get applications available for user's subscription.

        ``GET /sub/{token}/apps``

        Args:
            token:

        Returns:
            list[models.Application]
        """
        path = _fmt("/sub/{token}/apps", {"token": token})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return [models.Application.model_validate(x) for x in data]

    async def get_sub_user_usage(
        self,
        token: str,
        *,
        period: models.Period | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
    ) -> models.UserUsageStatsList:
        """Get Sub User Usage.

        Fetches the usage statistics for the user within a specified date range.

        ``GET /sub/{token}/usage``

        Args:
            token:
            period: Query parameter.
            start: Query parameter.
            end: Query parameter.

        Returns:
            models.UserUsageStatsList
        """
        path = _fmt("/sub/{token}/usage", {"token": token})
        params = _clean({"period": period, "start": start, "end": end})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserUsageStatsList.model_validate(data)

    async def user_subscription_with_client_type(
        self,
        token: str,
        client_type: models.ConfigFormat | str,
        *,
        x_hwid: str | None = None,
        x_device_os: str | None = None,
        x_ver_os: str | None = None,
        x_device_model: str | None = None,
    ) -> Any:
        """User Subscription With Client Type.

        Provides a subscription link based on the specified client type (e.g., Clash, V2Ray).

        ``GET /sub/{token}/{client_type}``

        Args:
            token:
            client_type:
            x_hwid: Header ``X-HWID``.
            x_device_os: Header ``X-Device-OS``.
            x_ver_os: Header ``X-Ver-OS``.
            x_device_model: Header ``X-Device-Model``.

        Returns:
            Any
        """
        path = _fmt("/sub/{token}/{client_type}", {"token": token, "client_type": client_type})
        params = None
        headers = _clean(
            {"X-HWID": x_hwid, "X-Device-OS": x_device_os, "X-Ver-OS": x_ver_os, "X-Device-Model": x_device_model}
        )
        return await self._http.request("get", path, params=params, headers=headers)
