"""System endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class SystemResource:
    """System endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def get_system_stats(self, *, admin_username: str | None = None) -> models.SystemStats:
        """Get System Stats.

        Fetch system stats including memory, CPU, disk, and user metrics.

        ``GET /api/system``

        Args:
            admin_username: Query parameter.

        Returns:
            models.SystemStats
        """
        path = "/api/system"
        params = _clean({"admin_username": admin_username})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.SystemStats.model_validate(data)

    async def get_system_resource_stats(self) -> models.SystemResourceStats:
        """Get System Resource Stats.

        Fetch system resource stats without user metrics.

        ``GET /api/system/resources``

        Returns:
            models.SystemResourceStats
        """
        path = "/api/system/resources"
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.SystemResourceStats.model_validate(data)

    async def get_system_users_stats(self, *, admin_username: str | None = None) -> models.SystemUsersStats:
        """Get System Users Stats.

        Fetch user stats and traffic metrics without system resource stats.

        ``GET /api/system/users``

        Args:
            admin_username: Query parameter.

        Returns:
            models.SystemUsersStats
        """
        path = "/api/system/users"
        params = _clean({"admin_username": admin_username})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.SystemUsersStats.model_validate(data)

    async def get_inbounds(self) -> list[str]:
        """Get Inbounds.

        Retrieve inbound configurations grouped by protocol.

        ``GET /api/inbounds``

        Returns:
            list[str]
        """
        path = "/api/inbounds"
        params = None
        headers = None
        return await self._http.request("get", path, params=params, headers=headers)

    async def get_inbound_details(self) -> list[models.InboundSummary]:
        """Get Inbound Details.

        Retrieve lightweight inbound metadata for dashboard forms.

        ``GET /api/inbounds/details``

        Returns:
            list[models.InboundSummary]
        """
        path = "/api/inbounds/details"
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return [models.InboundSummary.model_validate(x) for x in data]

    async def get_wireguard_subnets(self) -> list[models.WireGuardSubnetUsage]:
        """Get Wireguard Subnets.

        Per-subnet WireGuard address usage: capacity, used/free counts and the first free IPs.

        ``GET /api/wireguard/subnets``

        Returns:
            list[models.WireGuardSubnetUsage]
        """
        path = "/api/wireguard/subnets"
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return [models.WireGuardSubnetUsage.model_validate(x) for x in data]

    async def get_workers_health(self) -> models.WorkersHealth:
        """Get Workers Health.

        ``GET /api/workers/health``

        Returns:
            models.WorkersHealth
        """
        path = "/api/workers/health"
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.WorkersHealth.model_validate(data)
