"""User endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class UsersResource:
    """User endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def create_user(self, *, body: models.UserCreate | dict[str, Any]) -> models.UserResponse:
        """Create User.

        Create a new user

        - **username**: 3 to 32 characters, can include a-z, 0-9, and underscores.
        - **status**: User's status, defaults to `active`. Special rules if `on_hold`.
        - **expire**: UTC datetime for account expiration. Use `0` for unlimited.
        - **data_limit**: Max data usage in bytes (e.g., `1073741824` for 1GB). `0` means unlimited.
        - **data_limit_reset_strategy**: Defines how/if data limit resets. `no_reset` means it never resets.
        - **proxy_settings**: Dictionary of protocol settings (e.g., `vmess`, `vless`) will generate data for all protocol by default.
        - **group_ids**: List of group IDs to assign to the user.
        - **note**: Optional text field for additional user information or notes.
        - **on_hold_timeout**: UTC timestamp when `on_hold` status should start or end.
        - **on_hold_expire_duration**: Duration (in seconds) for how long the user should stay in `on_hold` status.
        - **next_plan**: Next user plan (resets after use).

        ``POST /api/user``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.UserResponse
        """
        path = "/api/user"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.UserResponse.model_validate(data)

    async def modify_user(self, username: str, *, body: models.UserModify | dict[str, Any]) -> models.UserResponse:
        """Modify User.

        Modify an existing user

        - **username**: Cannot be changed. Used to identify the user.
        - **status**: User's new status. Can be 'active', 'disabled', 'on_hold', 'limited', or 'expired'.
        - **expire**: UTC datetime for new account expiration. Set to `0` for unlimited, `null` for no change.
        - **data_limit**: New max data usage in bytes (e.g., `1073741824` for 1GB). Set to `0` for unlimited, `null` for no change.
        - **data_limit_reset_strategy**: New strategy for data limit reset. Options include 'daily', 'weekly', 'monthly', or 'no_reset'.
        - **proxies**: Dictionary of new protocol settings (e.g., `vmess`, `vless`). Empty dictionary means no change.
        - **group_ids**: List of new group IDs to assign to the user. Empty list means no change.
        - **note**: New optional text for additional user information or notes. `null` means no change.
        - **on_hold_timeout**: New UTC timestamp for when `on_hold` status should start or end. Only applicable if status is changed to 'on_hold'.
        - **on_hold_expire_duration**: New duration (in seconds) for how long the user should stay in `on_hold` status. Only applicable if status is changed to 'on_hold'.
        - **next_plan**: Next user plan (resets after use).

        Note: Fields set to `null` or omitted will not be modified.

        ``PUT /api/user/{username}``

        Args:
            username:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/{username}", {"username": username})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.UserResponse.model_validate(data)

    async def remove_user(self, username: str) -> None:
        """Remove User.

        Remove a user

        ``DELETE /api/user/{username}``

        Args:
            username:

        Returns:
            None
        """
        path = _fmt("/api/user/{username}", {"username": username})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def get_user(self, username: str) -> models.UserResponse:
        """Get User.

        Get user information

        ``GET /api/user/{username}``

        Args:
            username:

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/{username}", {"username": username})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def modify_user_by_username(
        self, username: str, *, body: models.UserModify | dict[str, Any]
    ) -> models.UserResponse:
        """Modify User By Username.

        ``PUT /api/user/by-username/{username}``

        Args:
            username:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/by-username/{username}", {"username": username})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.UserResponse.model_validate(data)

    async def remove_user_by_username(self, username: str) -> None:
        """Remove User By Username.

        ``DELETE /api/user/by-username/{username}``

        Args:
            username:

        Returns:
            None
        """
        path = _fmt("/api/user/by-username/{username}", {"username": username})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def get_user_by_username(self, username: str) -> models.UserResponse:
        """Get User By Username.

        ``GET /api/user/by-username/{username}``

        Args:
            username:

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/by-username/{username}", {"username": username})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def modify_user_by_id(self, user_id: int, *, body: models.UserModify | dict[str, Any]) -> models.UserResponse:
        """Modify User By Id.

        ``PUT /api/user/by-id/{user_id}``

        Args:
            user_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/by-id/{user_id}", {"user_id": user_id})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.UserResponse.model_validate(data)

    async def remove_user_by_id(self, user_id: int) -> None:
        """Remove User By Id.

        ``DELETE /api/user/by-id/{user_id}``

        Args:
            user_id:

        Returns:
            None
        """
        path = _fmt("/api/user/by-id/{user_id}", {"user_id": user_id})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def get_user_by_id(self, user_id: int) -> models.UserResponse:
        """Get User By Id.

        ``GET /api/user/by-id/{user_id}``

        Args:
            user_id:

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/by-id/{user_id}", {"user_id": user_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def set_user_disabled(
        self, username: str, *, body: models.UserStatusToggle | dict[str, Any]
    ) -> models.UserResponse:
        """Set User Disabled.

        ``PUT /api/user/{username}/disabled``

        Args:
            username:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/{username}/disabled", {"username": username})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.UserResponse.model_validate(data)

    async def set_user_disabled_by_username(
        self, username: str, *, body: models.UserStatusToggle | dict[str, Any]
    ) -> models.UserResponse:
        """Set User Disabled By Username.

        ``PUT /api/user/by-username/{username}/disabled``

        Args:
            username:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/by-username/{username}/disabled", {"username": username})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.UserResponse.model_validate(data)

    async def set_user_disabled_by_id(
        self, user_id: int, *, body: models.UserStatusToggle | dict[str, Any]
    ) -> models.UserResponse:
        """Set User Disabled By Id.

        ``PUT /api/user/by-id/{user_id}/disabled``

        Args:
            user_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/by-id/{user_id}/disabled", {"user_id": user_id})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.UserResponse.model_validate(data)

    async def reset_user_data_usage(self, username: str) -> models.UserResponse:
        """Reset User Data Usage.

        Reset user data usage

        ``POST /api/user/{username}/reset``

        Args:
            username:

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/{username}/reset", {"username": username})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def reset_user_data_usage_by_username(self, username: str) -> models.UserResponse:
        """Reset User Data Usage By Username.

        ``POST /api/user/by-username/{username}/reset``

        Args:
            username:

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/by-username/{username}/reset", {"username": username})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def reset_user_data_usage_by_id(self, user_id: int) -> models.UserResponse:
        """Reset User Data Usage By Id.

        ``POST /api/user/by-id/{user_id}/reset``

        Args:
            user_id:

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/by-id/{user_id}/reset", {"user_id": user_id})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def revoke_user_subscription(self, username: str) -> models.UserResponse:
        """Revoke User Subscription.

        Revoke users subscription (Subscription link and proxies)

        ``POST /api/user/{username}/revoke_sub``

        Args:
            username:

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/{username}/revoke_sub", {"username": username})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def revoke_user_subscription_by_username(self, username: str) -> models.UserResponse:
        """Revoke User Subscription By Username.

        ``POST /api/user/by-username/{username}/revoke_sub``

        Args:
            username:

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/by-username/{username}/revoke_sub", {"username": username})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def revoke_user_subscription_by_id(self, user_id: int) -> models.UserResponse:
        """Revoke User Subscription By Id.

        ``POST /api/user/by-id/{user_id}/revoke_sub``

        Args:
            user_id:

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/by-id/{user_id}/revoke_sub", {"user_id": user_id})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def reset_users_data_usage(self) -> Any:
        """Reset Users Data Usage.

        Reset all users data usage

        ``POST /api/users/reset``

        Returns:
            Any
        """
        path = "/api/users/reset"
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers)

    async def get_users_sub_update_chart(
        self,
        *,
        user_id: int | None = None,
        username: str | None = None,
        admin_id: int | None = None,
        period: models.Period | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
    ) -> models.UserSubscriptionUpdateChart:
        """Get Users Sub Update Chart.

        Get subscription agent distribution over a period (optionally filtered by user_id/username).

        ``GET /api/users/sub_update/chart``

        Args:
            user_id: Query parameter.
            username: Query parameter.
            admin_id: Query parameter.
            period: Query parameter.
            start: Query parameter.
            end: Query parameter.

        Returns:
            models.UserSubscriptionUpdateChart
        """
        path = "/api/users/sub_update/chart"
        params = _clean(
            {
                "user_id": user_id,
                "username": username,
                "admin_id": admin_id,
                "period": period,
                "start": start,
                "end": end,
            }
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserSubscriptionUpdateChart.model_validate(data)

    async def set_owner(self, username: str, *, admin_username: str) -> models.UserResponse:
        """Set Owner.

        Set a new owner (admin) for a user.

        ``PUT /api/user/{username}/set_owner``

        Args:
            username:
            admin_username: Query parameter.

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/{username}/set_owner", {"username": username})
        params = _clean({"admin_username": admin_username})
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def set_owner_by_username(self, username: str, *, admin_username: str) -> models.UserResponse:
        """Set Owner By Username.

        ``PUT /api/user/by-username/{username}/set_owner``

        Args:
            username:
            admin_username: Query parameter.

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/by-username/{username}/set_owner", {"username": username})
        params = _clean({"admin_username": admin_username})
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def set_owner_by_id(self, user_id: int, *, admin_username: str) -> models.UserResponse:
        """Set Owner By Id.

        ``PUT /api/user/by-id/{user_id}/set_owner``

        Args:
            user_id:
            admin_username: Query parameter.

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/by-id/{user_id}/set_owner", {"user_id": user_id})
        params = _clean({"admin_username": admin_username})
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def active_next_plan(self, username: str) -> models.UserResponse:
        """Active Next Plan.

        Reset user by next plan

        ``POST /api/user/{username}/active_next``

        Args:
            username:

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/{username}/active_next", {"username": username})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def active_next_plan_by_username(self, username: str) -> models.UserResponse:
        """Active Next Plan By Username.

        ``POST /api/user/by-username/{username}/active_next``

        Args:
            username:

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/by-username/{username}/active_next", {"username": username})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def active_next_plan_by_id(self, user_id: int) -> models.UserResponse:
        """Active Next Plan By Id.

        ``POST /api/user/by-id/{user_id}/active_next``

        Args:
            user_id:

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/by-id/{user_id}/active_next", {"user_id": user_id})
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers)
        return models.UserResponse.model_validate(data)

    async def get_user_subscription_by_id(self, user_id: int, client_type: models.ConfigFormat | str) -> Any:
        """Get User Subscription By Id.

        Get a user's subscription content in the requested format.

        ``GET /api/user/{user_id}/subscription/{client_type}``

        Args:
            user_id:
            client_type:

        Returns:
            Any
        """
        path = _fmt("/api/user/{user_id}/subscription/{client_type}", {"user_id": user_id, "client_type": client_type})
        params = None
        headers = None
        return await self._http.request("get", path, params=params, headers=headers)

    async def get_user_sub_update_list(
        self, username: str, *, offset: int | None = None, limit: int | None = None
    ) -> models.UserSubscriptionUpdateList:
        """Get User Sub Update List.

        Get user subscription agent list

        ``GET /api/user/{username}/sub_update``

        Args:
            username:
            offset: Query parameter.
            limit: Query parameter.

        Returns:
            models.UserSubscriptionUpdateList
        """
        path = _fmt("/api/user/{username}/sub_update", {"username": username})
        params = _clean({"offset": offset, "limit": limit})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserSubscriptionUpdateList.model_validate(data)

    async def get_user_sub_update_list_by_username(
        self, username: str, *, offset: int | None = None, limit: int | None = None
    ) -> models.UserSubscriptionUpdateList:
        """Get User Sub Update List By Username.

        ``GET /api/user/by-username/{username}/sub_update``

        Args:
            username:
            offset: Query parameter.
            limit: Query parameter.

        Returns:
            models.UserSubscriptionUpdateList
        """
        path = _fmt("/api/user/by-username/{username}/sub_update", {"username": username})
        params = _clean({"offset": offset, "limit": limit})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserSubscriptionUpdateList.model_validate(data)

    async def get_user_sub_update_list_by_id(
        self, user_id: int, *, offset: int | None = None, limit: int | None = None
    ) -> models.UserSubscriptionUpdateList:
        """Get User Sub Update List By Id.

        ``GET /api/user/by-id/{user_id}/sub_update``

        Args:
            user_id:
            offset: Query parameter.
            limit: Query parameter.

        Returns:
            models.UserSubscriptionUpdateList
        """
        path = _fmt("/api/user/by-id/{user_id}/sub_update", {"user_id": user_id})
        params = _clean({"offset": offset, "limit": limit})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserSubscriptionUpdateList.model_validate(data)

    async def get_users(
        self,
        *,
        offset: int | None = None,
        limit: int | None = None,
        ids: list[int] | None = None,
        username: list[str] | None = None,
        usernames: list[str] | None = None,
        admin: list[str] | None = None,
        admin_ids: list[int] | None = None,
        group: list[int] | None = None,
        no_group: bool | None = None,
        search: str | None = None,
        status: models.UserStatus | list[models.UserStatus] | None = None,
        sort: str | None = None,
        proxy_id: str | None = None,
        data_limit_reset_strategy: models.DataLimitResetStrategy | list[models.DataLimitResetStrategy] | None = None,
        data_limit_min: int | None = None,
        data_limit_max: int | None = None,
        expire_after: datetime | None = None,
        expire_before: datetime | None = None,
        online_after: datetime | None = None,
        online_before: datetime | None = None,
        online: bool | None = None,
        no_data_limit: bool | None = None,
        no_expire: bool | None = None,
        load_sub: bool | None = None,
    ) -> models.UsersResponse:
        """Get Users.

        Get all users

        ``GET /api/users``

        Args:
            offset: Query parameter.
            limit: Query parameter.
            ids: Query parameter.
            username: Query parameter.
            usernames: Query parameter.
            admin: Query parameter.
            admin_ids: Query parameter.
            group: Query parameter.
            no_group: Query parameter.
            search: Query parameter.
            status: Query parameter.
            sort: Query parameter.
            proxy_id: Query parameter.
            data_limit_reset_strategy: Query parameter.
            data_limit_min: Query parameter.
            data_limit_max: Query parameter.
            expire_after: Query parameter.
            expire_before: Query parameter.
            online_after: Query parameter.
            online_before: Query parameter.
            online: Query parameter.
            no_data_limit: Query parameter.
            no_expire: Query parameter.
            load_sub: Query parameter.

        Returns:
            models.UsersResponse
        """
        path = "/api/users"
        params = _clean(
            {
                "offset": offset,
                "limit": limit,
                "ids": ids,
                "username": username,
                "usernames": usernames,
                "admin": admin,
                "admin_ids": admin_ids,
                "group": group,
                "no_group": no_group,
                "search": search,
                "status": status,
                "sort": sort,
                "proxy_id": proxy_id,
                "data_limit_reset_strategy": data_limit_reset_strategy,
                "data_limit_min": data_limit_min,
                "data_limit_max": data_limit_max,
                "expire_after": expire_after,
                "expire_before": expire_before,
                "online_after": online_after,
                "online_before": online_before,
                "online": online,
                "no_data_limit": no_data_limit,
                "no_expire": no_expire,
                "load_sub": load_sub,
            }
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UsersResponse.model_validate(data)

    async def get_users_simple(
        self,
        *,
        ids: list[int] | None = None,
        usernames: list[str] | None = None,
        offset: int | None = None,
        limit: int | None = None,
        search: str | None = None,
        sort: str | None = None,
        all: bool | None = None,
    ) -> models.UsersSimpleResponse:
        """Get lightweight user list.

        Returns only id and username for users. Optimized for dropdowns and autocomplete.

        ``GET /api/users/simple``

        Args:
            ids: Query parameter.
            usernames: Query parameter.
            offset: Query parameter.
            limit: Query parameter.
            search: Query parameter.
            sort: Query parameter.
            all: Query parameter.

        Returns:
            models.UsersSimpleResponse
        """
        path = "/api/users/simple"
        params = _clean(
            {
                "ids": ids,
                "usernames": usernames,
                "offset": offset,
                "limit": limit,
                "search": search,
                "sort": sort,
                "all": all,
            }
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UsersSimpleResponse.model_validate(data)

    async def get_user_usage(
        self,
        username: str,
        *,
        period: models.Period | None = None,
        node_id: int | None = None,
        group_by_node: bool | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
    ) -> models.UserUsageStatsList:
        """Get User Usage.

        Get users usage

        ``GET /api/user/{username}/usage``

        Args:
            username:
            period: Query parameter.
            node_id: Query parameter.
            group_by_node: Query parameter.
            start: Query parameter.
            end: Query parameter.

        Returns:
            models.UserUsageStatsList
        """
        path = _fmt("/api/user/{username}/usage", {"username": username})
        params = _clean(
            {"period": period, "node_id": node_id, "group_by_node": group_by_node, "start": start, "end": end}
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserUsageStatsList.model_validate(data)

    async def get_user_usage_by_username(
        self,
        username: str,
        *,
        period: models.Period | None = None,
        node_id: int | None = None,
        group_by_node: bool | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
    ) -> models.UserUsageStatsList:
        """Get User Usage By Username.

        ``GET /api/user/by-username/{username}/usage``

        Args:
            username:
            period: Query parameter.
            node_id: Query parameter.
            group_by_node: Query parameter.
            start: Query parameter.
            end: Query parameter.

        Returns:
            models.UserUsageStatsList
        """
        path = _fmt("/api/user/by-username/{username}/usage", {"username": username})
        params = _clean(
            {"period": period, "node_id": node_id, "group_by_node": group_by_node, "start": start, "end": end}
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserUsageStatsList.model_validate(data)

    async def get_user_usage_by_id(
        self,
        user_id: int,
        *,
        period: models.Period | None = None,
        node_id: int | None = None,
        group_by_node: bool | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
    ) -> models.UserUsageStatsList:
        """Get User Usage By Id.

        ``GET /api/user/by-id/{user_id}/usage``

        Args:
            user_id:
            period: Query parameter.
            node_id: Query parameter.
            group_by_node: Query parameter.
            start: Query parameter.
            end: Query parameter.

        Returns:
            models.UserUsageStatsList
        """
        path = _fmt("/api/user/by-id/{user_id}/usage", {"user_id": user_id})
        params = _clean(
            {"period": period, "node_id": node_id, "group_by_node": group_by_node, "start": start, "end": end}
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserUsageStatsList.model_validate(data)

    async def get_users_usage(
        self,
        *,
        period: models.Period | None = None,
        node_id: int | None = None,
        group_by_node: bool | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
        admin: list[str] | None = None,
    ) -> models.UserUsageStatsList:
        """Get Users Usage.

        Get all users usage

        ``GET /api/users/usage``

        Args:
            period: Query parameter.
            node_id: Query parameter.
            group_by_node: Query parameter.
            start: Query parameter.
            end: Query parameter.
            admin: Query parameter.

        Returns:
            models.UserUsageStatsList
        """
        path = "/api/users/usage"
        params = _clean(
            {
                "period": period,
                "node_id": node_id,
                "group_by_node": group_by_node,
                "start": start,
                "end": end,
                "admin": admin,
            }
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserUsageStatsList.model_validate(data)

    async def get_user_ips(self, user_id: int, *, days: int | None = None) -> models.UserIpSeenList:
        """Get User Ips.

        Source IPs the user connected from, per node, with first/last sighting and GeoIP.

        ``GET /api/user/by-id/{user_id}/ips``

        Args:
            user_id:
            days: Query parameter.

        Returns:
            models.UserIpSeenList
        """
        path = _fmt("/api/user/by-id/{user_id}/ips", {"user_id": user_id})
        params = _clean({"days": days})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserIpSeenList.model_validate(data)

    async def get_user_events(self, user_id: int, *, limit: int | None = None) -> models.UserEventList:
        """Get User Events.

        Timeline of what happened to the user: creation, edits, resets, status changes.

        ``GET /api/user/by-id/{user_id}/events``

        Args:
            user_id:
            limit: Query parameter.

        Returns:
            models.UserEventList
        """
        path = _fmt("/api/user/by-id/{user_id}/events", {"user_id": user_id})
        params = _clean({"limit": limit})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserEventList.model_validate(data)

    async def get_recent_user_events(self, *, limit: int | None = None) -> models.RecentEventList:
        """Get Recent User Events.

        The latest things that happened to any user the caller may see: creations, holds, expiries, resets.

        ``GET /api/users/events``

        Args:
            limit: Query parameter.

        Returns:
            models.RecentEventList
        """
        path = "/api/users/events"
        params = _clean({"limit": limit})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.RecentEventList.model_validate(data)

    async def get_suspicious_users(self, *, days: int | None = None) -> models.SuspiciousUsersList:
        """Get Suspicious Users.

        Users seen from more IPs or countries than ABUSE_MAX_* allow in the window.

        ``GET /api/users/suspicious``

        Args:
            days: Query parameter.

        Returns:
            models.SuspiciousUsersList
        """
        path = "/api/users/suspicious"
        params = _clean({"days": days})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.SuspiciousUsersList.model_validate(data)

    async def geoip_lookup(self, *, ips: str) -> dict[str, Any]:
        """Geoip Lookup.

        Country and city of up to 200 comma-separated IPs from the offline GeoIP database.

        ``GET /api/users/geoip``

        Args:
            ips: Query parameter.

        Returns:
            dict[str, Any]
        """
        path = "/api/users/geoip"
        params = _clean({"ips": ips})
        headers = None
        return await self._http.request("get", path, params=params, headers=headers)

    async def get_top_users_usage(
        self,
        *,
        limit: int | None = None,
        period: models.Period | None = None,
        node_id: int | None = None,
        group_by_node: bool | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
        admin: list[str] | None = None,
    ) -> models.TopUsersUsageList:
        """Get Top Users Usage.

        Users with the most traffic in the range.

        ``GET /api/users/top_usage``

        Args:
            limit: Query parameter.
            period: Query parameter.
            node_id: Query parameter.
            group_by_node: Query parameter.
            start: Query parameter.
            end: Query parameter.
            admin: Query parameter.

        Returns:
            models.TopUsersUsageList
        """
        path = "/api/users/top_usage"
        params = _clean(
            {
                "limit": limit,
                "period": period,
                "node_id": node_id,
                "group_by_node": group_by_node,
                "start": start,
                "end": end,
                "admin": admin,
            }
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.TopUsersUsageList.model_validate(data)

    async def get_users_count_metric(
        self,
        metric: models.UserCountMetric | str,
        *,
        period: models.Period | None = None,
        node_id: int | None = None,
        group_by_node: bool | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
        admin: list[str] | None = None,
    ) -> models.UserCountMetricStatsList:
        """Get Users Count Metric.

        Get one users activity/status count metric from usage rows.

        ``GET /api/users/counts/{metric}``

        Args:
            metric:
            period: Query parameter.
            node_id: Query parameter.
            group_by_node: Query parameter.
            start: Query parameter.
            end: Query parameter.
            admin: Query parameter.

        Returns:
            models.UserCountMetricStatsList
        """
        path = _fmt("/api/users/counts/{metric}", {"metric": metric})
        params = _clean(
            {
                "period": period,
                "node_id": node_id,
                "group_by_node": group_by_node,
                "start": start,
                "end": end,
                "admin": admin,
            }
        )
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserCountMetricStatsList.model_validate(data)

    async def get_expired_users(
        self,
        *,
        admin_username: str | None = None,
        target: str | None = None,
        expired_after: datetime | None = None,
        expired_before: datetime | None = None,
        dry_run: bool | None = None,
    ) -> list[str]:
        """Get Expired Users.

        Get cleanup-target users in the specified scope.

        - **target**: `expired` | `limited` | `on_hold` | `disabled`
        - **expired_after** / **expired_before** UTC datetime (optional)
        - For `expired`: filters by expiration date.
        - For `limited` / `on_hold` / `disabled`: filters by last_status_change (when they entered that status).

        ``GET /api/users/expired``

        Args:
            admin_username: Query parameter.
            target: Query parameter.
            expired_after: Query parameter.
            expired_before: Query parameter.
            dry_run: Query parameter.

        Returns:
            list[str]
        """
        path = "/api/users/expired"
        params = _clean(
            {
                "admin_username": admin_username,
                "target": target,
                "expired_after": expired_after,
                "expired_before": expired_before,
                "dry_run": dry_run,
            }
        )
        headers = None
        return await self._http.request("get", path, params=params, headers=headers)

    async def delete_expired_users(
        self,
        *,
        admin_username: str | None = None,
        target: str | None = None,
        expired_after: datetime | None = None,
        expired_before: datetime | None = None,
        dry_run: bool | None = None,
    ) -> models.RemoveUsersResponse:
        """Delete Expired Users.

        Delete cleanup-target users in the specified scope.

        - **target**: `expired` | `limited` | `on_hold` | `disabled`
        - **expired_after** / **expired_before** UTC datetime (optional)
        - For `expired`: filters by expiration date.
        - For `limited` / `on_hold` / `disabled`: filters by last_status_change (when they entered that status).
        - **dry_run**: if true, returns users that would be deleted without deleting them.

        ``DELETE /api/users/expired``

        Args:
            admin_username: Query parameter.
            target: Query parameter.
            expired_after: Query parameter.
            expired_before: Query parameter.
            dry_run: Query parameter.

        Returns:
            models.RemoveUsersResponse
        """
        path = "/api/users/expired"
        params = _clean(
            {
                "admin_username": admin_username,
                "target": target,
                "expired_after": expired_after,
                "expired_before": expired_before,
                "dry_run": dry_run,
            }
        )
        headers = None
        data = await self._http.request("delete", path, params=params, headers=headers)
        return models.RemoveUsersResponse.model_validate(data)

    async def bulk_delete_users(
        self, *, body: models.BulkUsersSelection | dict[str, Any]
    ) -> models.RemoveUsersResponse:
        """Bulk Delete Users.

        Delete selected users by ID.

        ``POST /api/users/bulk/delete``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.RemoveUsersResponse
        """
        path = "/api/users/bulk/delete"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.RemoveUsersResponse.model_validate(data)

    async def bulk_reset_users_data_usage(
        self, *, body: models.BulkUsersSelection | dict[str, Any]
    ) -> models.BulkUsersActionResponse:
        """Bulk Reset Users Data Usage.

        Reset usage for selected users by ID.

        ``POST /api/users/bulk/reset``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkUsersActionResponse
        """
        path = "/api/users/bulk/reset"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkUsersActionResponse.model_validate(data)

    async def bulk_disable_users(
        self, *, body: models.BulkUsersSelection | dict[str, Any]
    ) -> models.BulkUsersActionResponse:
        """Bulk Disable Users.

        Disable selected users by ID.

        ``POST /api/users/bulk/disable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkUsersActionResponse
        """
        path = "/api/users/bulk/disable"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkUsersActionResponse.model_validate(data)

    async def bulk_enable_users(
        self, *, body: models.BulkUsersSelection | dict[str, Any]
    ) -> models.BulkUsersActionResponse:
        """Bulk Enable Users.

        Enable selected users by ID.

        ``POST /api/users/bulk/enable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkUsersActionResponse
        """
        path = "/api/users/bulk/enable"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkUsersActionResponse.model_validate(data)

    async def bulk_revoke_users_subscription(
        self, *, body: models.BulkUsersSelection | dict[str, Any]
    ) -> models.BulkUsersActionResponse:
        """Bulk Revoke Users Subscription.

        Revoke subscriptions for selected users by ID.

        ``POST /api/users/bulk/revoke_sub``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkUsersActionResponse
        """
        path = "/api/users/bulk/revoke_sub"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkUsersActionResponse.model_validate(data)

    async def bulk_set_owner(
        self, *, body: models.BulkUsersSetOwner | dict[str, Any]
    ) -> models.BulkUsersActionResponse:
        """Bulk Set Owner.

        Set a new owner for selected users by ID.

        ``PUT /api/users/bulk/set_owner``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkUsersActionResponse
        """
        path = "/api/users/bulk/set_owner"
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.BulkUsersActionResponse.model_validate(data)

    async def create_user_from_template(
        self, *, body: models.CreateUserFromTemplate | dict[str, Any]
    ) -> models.UserResponse:
        """Create User From Template.

        ``POST /api/user/from_template``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.UserResponse
        """
        path = "/api/user/from_template"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.UserResponse.model_validate(data)

    async def bulk_create_users_from_template(
        self, *, body: models.BulkUsersFromTemplate | dict[str, Any]
    ) -> models.BulkUsersCreateResponse:
        """Bulk Create Users From Template.

        Bulk create users from a template using configurable username strategies.

        - Includes the template creation fields plus `count`, `strategy`, and `start_number` (for sequences).
        - **strategy**: Username generation strategy — `sequence` or `random`.
        - **start_number**: Optional starting suffix for `sequence` strategy. Defaults to `1` and does not parse numbers from the base username.

        Returns subscription URLs for created users.

        ``POST /api/users/bulk/from_template``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkUsersCreateResponse
        """
        path = "/api/users/bulk/from_template"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkUsersCreateResponse.model_validate(data)

    async def bulk_apply_template_to_users(
        self, *, body: models.BulkUsersApplyTemplate | dict[str, Any]
    ) -> models.BulkUsersActionResponse:
        """Bulk Apply Template To Users.

        Apply a user template to selected existing users by ID.

        ``POST /api/users/bulk/apply_template``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkUsersActionResponse
        """
        path = "/api/users/bulk/apply_template"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkUsersActionResponse.model_validate(data)

    async def modify_user_with_template(
        self, username: str, *, body: models.ModifyUserByTemplate | dict[str, Any]
    ) -> models.UserResponse:
        """Modify User With Template.

        ``PUT /api/user/from_template/{username}``

        Args:
            username:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/from_template/{username}", {"username": username})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.UserResponse.model_validate(data)

    async def modify_user_with_template_by_username(
        self, username: str, *, body: models.ModifyUserByTemplate | dict[str, Any]
    ) -> models.UserResponse:
        """Modify User With Template By Username.

        ``PUT /api/user/from_template/by-username/{username}``

        Args:
            username:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/from_template/by-username/{username}", {"username": username})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.UserResponse.model_validate(data)

    async def modify_user_with_template_by_id(
        self, user_id: int, *, body: models.ModifyUserByTemplate | dict[str, Any]
    ) -> models.UserResponse:
        """Modify User With Template By Id.

        ``PUT /api/user/from_template/by-id/{user_id}``

        Args:
            user_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.UserResponse
        """
        path = _fmt("/api/user/from_template/by-id/{user_id}", {"user_id": user_id})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.UserResponse.model_validate(data)

    async def bulk_modify_users_expire(self, *, body: models.BulkUser | dict[str, Any]) -> Any:
        """Bulk sum/sub to expire of users.

        Bulk expire users based on the provided criteria.

        - **amount**: amount to adjust the user's quota (in seconds, positive to increase, negative to decrease) required
        - **user_ids**: Optional list of user IDs to modify
        - **admins**: Optional list of admin IDs — their users will be targeted
        - **status**: Optional status to filter users (e.g., "expired", "active"), Empty means no filtering
        - **group_ids**: Optional list of group IDs to filter users by their group membership
        - **expire_after**: Optional UTC datetime to filter users whose expire date is on or after this date
        - **expire_before**: Optional UTC datetime to filter users whose expire date is on or before this date

        ``POST /api/users/bulk/expire``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            Any
        """
        path = "/api/users/bulk/expire"
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers, json=_dump(body))

    async def bulk_modify_users_datalimit(self, *, body: models.BulkUser | dict[str, Any]) -> Any:
        """Bulk sum/sub to data limit of users.

        Bulk modify users' data limit based on the provided criteria.

        - **amount**: amount to adjust the user's quota (positive to increase, negative to decrease) required
        - **user_ids**: Optional list of user IDs to modify
        - **admins**: Optional list of admin IDs — their users will be targeted
        - **status**: Optional status to filter users (e.g., "expired", "active"), Empty means no filtering
        - **group_ids**: Optional list of group IDs to filter users by their group membership
        - **expire_after**: Optional UTC datetime to filter users whose expire date is on or after this date
        - **expire_before**: Optional UTC datetime to filter users whose expire date is on or before this date

        ``POST /api/users/bulk/data_limit``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            Any
        """
        path = "/api/users/bulk/data_limit"
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers, json=_dump(body))

    async def bulk_modify_users_proxy_settings(self, *, body: models.BulkUsersProxy | dict[str, Any]) -> Any:
        """Bulk modify users proxy settings.

        ``POST /api/users/bulk/proxy_settings``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            Any
        """
        path = "/api/users/bulk/proxy_settings"
        params = None
        headers = None
        return await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
