"""User Template endpoints. Generated by scripts/generate.py; do not edit by hand."""

from __future__ import annotations

from collections.abc import AsyncIterator  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any  # noqa: F401

from ixraypy import models  # noqa: F401
from ixraypy._http import HttpTransport, _clean, _dump, _fmt  # noqa: F401


class UserTemplatesResource:
    """User Template endpoints."""

    def __init__(self, http: HttpTransport) -> None:
        self._http = http

    async def create_user_template(
        self, *, body: models.UserTemplateCreate | dict[str, Any]
    ) -> models.UserTemplateResponse:
        """Create User Template.

        Create a new user template

        - **name** can be up to 64 characters
        - **data_limit** must be in bytes and larger or equal to 0
        - **expire_duration** must be in seconds and larger or equat to 0
        - **group_ids** list of group ids

        ``POST /api/user_template``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.UserTemplateResponse
        """
        path = "/api/user_template"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.UserTemplateResponse.model_validate(data)

    async def get_user_template(self, template_id: int) -> models.UserTemplateResponse:
        """Get User Template.

        Get User Template information with id

        ``GET /api/user_template/{template_id}``

        Args:
            template_id:

        Returns:
            models.UserTemplateResponse
        """
        path = _fmt("/api/user_template/{template_id}", {"template_id": template_id})
        params = None
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserTemplateResponse.model_validate(data)

    async def modify_user_template(
        self, template_id: int, *, body: models.UserTemplateModify | dict[str, Any]
    ) -> models.UserTemplateResponse:
        """Modify User Template.

        Modify User Template

        - **name** can be up to 64 characters
        - **data_limit** must be in bytes and larger or equal to 0
        - **expire_duration** must be in seconds and larger or equat to 0
        - **group_ids** list of group ids

        ``PUT /api/user_template/{template_id}``

        Args:
            template_id:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.UserTemplateResponse
        """
        path = _fmt("/api/user_template/{template_id}", {"template_id": template_id})
        params = None
        headers = None
        data = await self._http.request("put", path, params=params, headers=headers, json=_dump(body))
        return models.UserTemplateResponse.model_validate(data)

    async def remove_user_template(self, template_id: int) -> None:
        """Remove User Template.

        Remove a User Template by its ID

        ``DELETE /api/user_template/{template_id}``

        Args:
            template_id:

        Returns:
            None
        """
        path = _fmt("/api/user_template/{template_id}", {"template_id": template_id})
        params = None
        headers = None
        await self._http.request("delete", path, params=params, headers=headers)
        return None

    async def get_user_templates(
        self, *, ids: list[int] | None = None, offset: int | None = None, limit: int | None = None
    ) -> list[models.UserTemplateResponse]:
        """Get User Templates.

        Get a list of User Templates with optional pagination

        ``GET /api/user_templates``

        Args:
            ids: Query parameter.
            offset: Query parameter.
            limit: Query parameter.

        Returns:
            list[models.UserTemplateResponse]
        """
        path = "/api/user_templates"
        params = _clean({"ids": ids, "offset": offset, "limit": limit})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return [models.UserTemplateResponse.model_validate(x) for x in data]

    async def get_user_templates_simple(
        self,
        *,
        ids: list[int] | None = None,
        offset: int | None = None,
        limit: int | None = None,
        search: str | None = None,
        sort: str | None = None,
        all: bool | None = None,
    ) -> models.UserTemplatesSimpleResponse:
        """Get lightweight user template list.

        Returns only id and name for user templates. Optimized for dropdowns and autocomplete.

        ``GET /api/user_templates/simple``

        Args:
            ids: Query parameter.
            offset: Query parameter.
            limit: Query parameter.
            search: Query parameter.
            sort: Query parameter.
            all: Query parameter.

        Returns:
            models.UserTemplatesSimpleResponse
        """
        path = "/api/user_templates/simple"
        params = _clean({"ids": ids, "offset": offset, "limit": limit, "search": search, "sort": sort, "all": all})
        headers = None
        data = await self._http.request("get", path, params=params, headers=headers)
        return models.UserTemplatesSimpleResponse.model_validate(data)

    async def bulk_delete_user_templates(
        self, *, body: models.BulkUserTemplateSelection | dict[str, Any]
    ) -> models.RemoveUserTemplatesResponse:
        """Bulk Delete User Templates.

        Delete selected user templates by ID.

        ``POST /api/user_templates/bulk/delete``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.RemoveUserTemplatesResponse
        """
        path = "/api/user_templates/bulk/delete"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.RemoveUserTemplatesResponse.model_validate(data)

    async def bulk_disable_user_templates(
        self, *, body: models.BulkUserTemplateSelection | dict[str, Any]
    ) -> models.BulkUserTemplatesActionResponse:
        """Bulk Disable User Templates.

        Disable selected user templates by ID.

        ``POST /api/user_templates/bulk/disable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkUserTemplatesActionResponse
        """
        path = "/api/user_templates/bulk/disable"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkUserTemplatesActionResponse.model_validate(data)

    async def bulk_enable_user_templates(
        self, *, body: models.BulkUserTemplateSelection | dict[str, Any]
    ) -> models.BulkUserTemplatesActionResponse:
        """Bulk Enable User Templates.

        Enable selected user templates by ID.

        ``POST /api/user_templates/bulk/enable``

        Args:
            body: Request payload (a model instance or a plain dict).

        Returns:
            models.BulkUserTemplatesActionResponse
        """
        path = "/api/user_templates/bulk/enable"
        params = None
        headers = None
        data = await self._http.request("post", path, params=params, headers=headers, json=_dump(body))
        return models.BulkUserTemplatesActionResponse.model_validate(data)
